# Voorwoord door Tom van Lamoen {.unnumbered}

Saifedean Ammous is meesterlijk in staat om de principes van de Oostenrijkse School op een concrete manier te presenteren en toegankelijk te maken voor iedereen die er voor het eerst mee in aanraking komt. Echter, dit werk tekortdoen door het te bestempelen als 'De Oostenrijkse School voor Dummies' doet geen recht aan de diepgang ervan. Op een bijzonder elegante wijze weet Ammous de essentie van deze economische benadering en de filosofie van het libertarisme samen te vatten tot een coherent geheel waarin geen enkele lacune te ontdekken valt. Hij opent zijn betoog met de opmerking dat hij dit boek graag gedurende zijn hele loopbaan als economisch docent bij de hand had gehad, om adequaat de vragen van zijn studenten te kunnen beantwoorden.

In de huidige samenleving vertonen alle vormen van menselijke interactie scheefgroei, voornamelijk doordat educatie over de basis van menselijk handelen in het huidige economische en monetaire systeem volledig ontbreekt. Voor mij heeft educatie en het verspreiden van het gedachtegoed over de huidige status quo, evenals mogelijke oplossingen, de hoogste prioriteit. Zijn boek *De Bitcoin Standaard* is voor mijzelf het meest geschonken boek, om dezelfde reden.

## Vrijwillig handelen

Vrijwillig handelen staat centraal in @sec-menselijk-handelen, waar we direct de diepte ingaan van de filosofische basis van praxeologie, het menselijk handelen, geïnspireerd door het werk van Ludwig von Mises -- *Human Action*. Als ik dan de kans krijg om mijn eigen visie te delen, benader ik dit vanuit mijn persoonlijke overtuiging. Ik beschouw de spirituele en morele kant van vrijwillig handelen als de basis van het 'voluntarisme'. De Oostenrijkse School toont aan dat de mens altijd bewust handelt, wat Mises 'doelgericht gedrag' noemt. Het lijkt de weg van de minste weerstand te volgen, maar het kan niet het volledige spectrum van handelen omvatten, aangezien menselijke acties niet voorspelbaar zijn.

In onze samenleving trachten diverse autoritaire krachten het menselijk handelen te beïnvloeden, terwijl de staat hierin een leidende rol speelt. Het bestaansrecht van de staat verkrijgt zij door dwang (belasting), waardoor alle regelgeving de keuzes van mensen beperkt. Dit vormt een ernstige bedreiging voor de vrijheid van het individu en is schadelijk voor de samenleving en economie. Onder het gezag van de staat kan er volgens mijn overtuiging geen vrije marktwerking bestaan, en bijgevolg geen vrijwillige actie.

## Vrijwillig eigendom

Vrijwillig eigendom is een ander kernprincipe van het libertarisme, geworteld in het eigendomsrecht. Zelfbeschikking over lichaam, arbeid en bezit is absoluut, zonder uitzondering of verwatering. Als je geen volledige zeggenschap hebt over je eigen lichaam, arbeid of bezit, ontbreekt zelfbeschikking automatisch. Vrijwilligheid ligt ook hier aan de basis. Het is altijd mogelijk om een deel van je lichaam, arbeid of bezit over te dragen aan een ander, maar alleen als dit voortkomt uit vrijwillige interactie valt dit onder zelfbeschikking. Zelfs bij een minimale overschrijding van de vrijwillige basis kan er sprake zijn van aanranding, slavernij of diefstal.

Vrijwilligheid vormt dus de basis van elke vorm van vrijheid. Als we kijken naar het concept van privacy, citeer ik graag uit het fantastische document genaamd *The Cypherpunk Manifesto*: 'Privacy is noodzakelijk voor een open samenleving in het elektronische tijdperk. Privacy is niet hetzelfde als geheimhouding. Een privékwestie is iets wat men niet wil dat de hele wereld weet, maar een geheime zaak is iets wat men niet aan iemand wil onthullen. Privacy is de kracht om selectief delen van zichzelf aan de wereld te openbaren.' Het selectief delen van informatie kan alleen vrijwillig plaatsvinden.

## Vrijwillige handel

Vrijwillige handel is naar mijn overtuiging enkel mogelijk in een vrije markt, waar alle transacties op volledig vrijwillige basis plaatsvinden. De vrije markt, zoals ik die voor ogen heb, is een manifestatie van de chaostheorie, ogenschijnlijk onvoorspelbaar van dichtbij, maar altijd geworteld in een rationele basis. Het is een optelsom van vrijwillig menselijk handelen, waarbij individuen gezamenlijk, volgens het principe van wisdom of the crowd, bepalen wat de vraag, het aanbod en de bijbehorende prijs voor een product of dienst zullen zijn. In deze dynamiek verschaffen marktsignalen constant inzicht in de actuele vraag en aanbod, waardoor de prijs een eerlijke weerspiegeling is van de huidige situatie.

Echter, als de vraag of het aanbod gemanipuleerd kunnen worden, kunnen bepaalde spelers in dit spel valsspelen. Dit betekent dat de signalen die de prijs bepalen verstoord worden, waardoor de prijs gemanipuleerd kan worden. Deze vorm van manipulatie komt op diverse manieren voor in de huidige markt, waarbij monopolies hun marktpositie misbruiken om zelf de prijs te kunnen bepalen. Dit is echter alleen mogelijk in een onvrije markt. Grote bedrijven lobbyen vaak voor overheidsinvloed om voordelen te verkrijgen ten opzichte van concurrentie, zoals belastingkortingen, subsidies, regulering, patenten of contracten met de overheid.

Een andere vorm van schadelijke en obscure overheidsinvloed, naast de eerder genoemde, is geld. Geld fungeert als de meetlat voor vraag en aanbod, en het is essentieel voor effectieve handel. Maar kunnen we erop vertrouwen dat het signaal dat geld ons geeft een rationeel beeld is? Onze overheid bewaakt het monopolie op ons geld, de euro, en banken en centrale banken kunnen dit fundament van onze samenleving manipuleren. Geld wordt ondersteund door arbeid, aangezien zo goed als alle mensen arbeid leveren voor hun inkomsten. Echter kan een kleine groep mensen eenvoudigweg op een knop drukken om ditzelfde geld te creëren, wat hen enorme macht geeft over alle facetten van de samenleving. Inflatie en de cyclus van economische boom en bust verstoren de signalen van vraag en aanbod, wat leidt tot bekende fenomenen zoals bubbels.

Het is duidelijk dat er geen sprake kan zijn van een vrije markt zolang we onderhevig zijn aan de manipulatie van een centrale bank. Dit zijn slechts enkele voorbeelden; men kan hele boeken vullen over dit onderwerp. Saifedean Ammous, als expert op dit gebied, slaagt erin om diepgaand alle facetten van deze economische filosofie toegankelijk en rationeel te presenteren.

Mijn laatste oproep is dan ook eenvoudig: gebruik dit boek als een wapen. Zorg ervoor dat de volgende generaties zich bewust worden van het systeem waarin we leven, zodat we kunnen bouwen aan een menselijke toekomst met een ware vrije markt.
