# Kapitalisme

::: blockquotebox
Uit de geschiedenis blijkt duidelijk dat privaat eigendom fundamenteel is, en onlosmakelijk verbonden is met een beschaving.

--- Ludwig von Mises
:::

[@130]

Een markteconomie, zoals besproken in het vorige hoofdstuk, betreft een sociale orde waarbij personen vanuit hun eigen belang economisch handelen, hetgeen ten goede komt aan alle betrokken partijen. Alle vormen van economisch handelen door individuen, zoals arbeid, kapitaalopbouw, technologische vernieuwing, handel en de productie van moderne energie, worden op vrijwillige basis door individuen uitgevoerd. Deze individuen maken gebruik van geldmiddelen om hun productiebereik uit te breiden en hun materiële welzijn aanzienlijk te verhogen in vergelijking met wat ze elk afzonderlijk zouden kunnen realiseren. De uitgebreide monetaire markteconomie faciliteert het ontstaan van het kapitalisme, een systeem van privaat eigendom van kapitaalgoederen waarin individuen vrij zijn om kapitaal aan te kopen en te verkopen en beslissingen te nemen over de inzet van hun kapitaal. Hierbij genieten ze de voordelen van productief gebruik ervan en dragen ze de nadelen van onproductief gebruik.

In *The End of Socialism and the Calculation Debate Revisited* legt Rothbard de criteria van Mises voor een markteconomie uit:

::: blockquotebox
Tijdens één van Mises seminaries aan de New York University, vroeg ik hem of hij, gezien het brede spectrum van economieën van een zuivere vrije markt tot puur totalitarisme, één criterium kon aanwijzen op basis waarvan hij kon zeggen dat een economie in wezen "socialistisch" was of dat het een markteconomie was. Enigszins tot mijn verbazing antwoordde hij onmiddellijk: "Ja, de sleutel is of de economie een aandelenmarkt heeft." Anders gezegd, of de economie een volwaardige markt heeft in eigendomstitels van land en kapitaalgoederen. Kortom: wordt de toewijzing van kapitaal in principe bepaald door de overheid of door particuliere eigenaren?
:::

[@131]

Voor Mises en de Oostenrijkse economen geldt de aanwezigheid van een aandelenmarkt als een effectieve toetssteen voor het kapitalisme, omdat het een duidelijk kenmerk is van een vrije markt voor productiemiddelen, toegankelijk voor iedereen in de maatschappij. Dit mechanisme zorgt ervoor dat kapitaal terechtkomt bij degenen die het het meest productief kunnen inzetten. Bedrijven die genoteerd staan op de aandelenmarkt bezitten een significant deel van het productiekapitaal in een samenleving, en dit kapitaal is voor iedereen beschikbaar om naar wens te kopen en verkopen. Als iemand meent dat hij kapitaalgoederen productiever kan inzetten dan de huidige eigenaar, kan hij deze overkopen door de gangbare marktprijs voor de aandelen te betalen. Iedereen is in staat om zijn spaargeld te investeren in een productieproces dat naar verwachting meer opbrengt dan het simpelweg aanhouden van contant geld. Degenen die succesvol zijn in het productief inzetten van hun kapitaal, maken winst en krijgen toegang tot meer kapitaalgoederen. Aan de andere kant zullen diegenen die hun kapitaal onproductief gebruiken, verliezen lijden, waardoor hun bezit een onhoudbare en kostbare vergissing wordt. Dit moedigt hen aan hun kapitaal te verkopen aan kopers die bereid zijn een hogere prijs te betalen omdat zij menen de middelen productiever te kunnen inzetten. Met een aandelenmarkt en een vrij kapitaalmarktmechanisme bestaan er geen beschermingsmechanismen voor kapitaaleigenaren die hun middelen ineffectief inzetten. Ze zullen hun bezit uiteindelijk verkopen aan efficiëntere gebruikers of blijven verliezen maken tot hun kapitaal volledig is uitgeput. In beide gevallen is kapitaal altijd onderdeel van een proces waarbij het verschuift naar meer productieve en bekwame handen. In een vrijemarkteconomie kunnen privileges of mandaten deze onstuitbare verschuiving naar een productiever gebruik van kapitaal principieel niet tegenhouden.

Economen van de Oostenrijkse School bieden, door kapitalisme te definiëren en te verklaren binnen de context van menselijk handelen, de meest uitgebreide en coherente benadering van kapitalisme. Hun visie dient als een krachtig en praktisch analytisch instrument voor het begrijpen van economische vraagstukken in de echte wereld en de dynamiek van een kapitalistisch systeem. Dit contrasteert sterk met de oppervlakkige behandeling van het onderwerp door andere economische scholen. Marxistische economen beschouwen kapitaal als een kwaadaardige kracht die kapitaalbezitters in staat stelt anderen uit te buiten en te onderdrukken. Ze negeren vaak de voordelen die kapitaal aan werknemers biedt, zoals verhoogde productiviteit, de kosten verbonden aan het bezitten ervan in de vorm van opportuniteitskosten, en de verantwoordelijkheden en risico's die eigendom met zich meebrengt. Tegelijkertijd beschouwen de meeste mainstream economen kapitaal als een geaggregeerd geheel --- een homogene massa die zelfonderhoudend is en ingezet wordt voor productie. Beide perspectieven missen het belang van privaat eigendom voor de groei van kapitaal en de essentiële rol van een vrije markt in het toewijzen van kapitaal aan de meest productieve toepassingen. Door de cruciale functie van kapitaalmarkten over het hoofd te zien, laten beide economische scholen hun aanhangers verkeerdelijk geloven dat kapitalistische economische productie kan bestaan in een systeem met beperkt privaat eigendom en vrije handel van productiemiddelen.

De waarde van kapitaalgoederen is subjectief en hangt af van hoe individuen ze waarderen. Ze is niet inherent of intrinsiek aanwezig. Of iets al dan niet een kapitaalgoed is, hangt volledig af van het oordeel en de handelingen van de persoon die het in bezit heeft. Bijvoorbeeld, een computer ingezet om games te spelen, geldt als een consumptiegoed. Dezelfde computer van een professionele grafisch ontwerper wordt echter beschouwd als een kapitaalgoed. Zonder de mogelijkheid om kapitaalgoederen te kopen met de bedoeling om winst te maken, hebben mensen weinig motivatie om kapitaal te verzamelen en te behouden. Als er geen kans is om kapitaal te ruilen voor financieel voordeel, ontbreekt het mechanisme om te garanderen dat kapitaal productief wordt ingezet. Hierdoor voorkomt men dat het in handen valt van mensen die het verspillen en de waarde ervan verlagen. Kapitaal moet men niet zien als een verzameling machines, maar als een concept dat, net als een levend organisme, overleeft in een ecosysteem. In dit ecosysteem wordt het voortdurend gewaardeerd en verhandeld door actieve individuen. Daarom is het niet zinvol om te praten over een kapitaalvoorraad in een samenleving zonder rekening te houden met de individuen. Zij waarderen de kapitaalgoederen zonder beperkingen, zetten ze in voor productie en profiteren ervan. Kapitaal zonder markteconomie is zoals een vis op het droge: een slap, levenloos omhulsel van wat ooit was.

## Kapitaalmarkten

Het komt vaak voor dat leken, politici en mainstream economen landen bestempelen als zijnde socialistisch of kapitalistisch, zonder daarbij een heldere definitie te hanteren om deze labels te rechtvaardigen. De criteria van Mises bieden ons echter een zeer effectieve methode om te begrijpen wat een kapitalistische economie inhoudt en wat een socialistische economie kenmerkt.

Een economie die geen aandelenmarkt heeft ontwikkeld, is geen kapitalistische markteconomie, omdat het niet het niveau van economische specialisatie en een verlengde kapitaalstructuur van de productie heeft ontwikkeld die nodig zijn om een markt voor kapitaal te ontwikkelen. Een economie waarvan de aandelenmarkt onder dwang door de overheid wordt gesloten, is een socialistische economie, omdat het kapitaal uit het domein van de marktconcurrentie is weggehaald en in handen is gegeven van bureaucraten die het niet bezitten, er niet legitiem van kunnen profiteren en geen economische calculatie te kunnen verrichten om te beslissen wat de beste productiemethoden zijn om het te gebruiken. Het criterium van Mises stelt ons in staat om economieën in te delen in drie categorieën: pre-kapitalistisch, kapitalistisch en socialistisch. De geschiedenis van de meeste landen in de wereld is de positieve ontwikkeling van pre-kapitalisme naar kapitalisme, onderbroken door rampzalige omleidingen naar socialistische verwoesting.

De Russische aandelenmarkt werd in het begin van de achttiende eeuw opgericht door een decreet van Peter de Grote. Dit was een tijd waarin Rusland zich ontwikkelde van een agrarische naar een kapitalistische economie. De beurzen bleven functioneren tot de bolsjewieken in 1917 door een staatsgreep aan de macht kwamen en Rusland overging op een socialistisch economisch systeem. Na het einde van het bolsjewistische regime hervatte de aandelenmarkt zijn activiteiten in 1991, waarmee het land terugkeerde naar een kapitalistische economie. De verwoestende impact van het socialisme op Rusland valt samen met de periode waarin de aandelenmarkt was gesloten.

Duitsland biedt een ander inzichtelijk voorbeeld van het belang van de criteria van Mises. Al in de zestiende eeuw werden verschillende effectenbeurzen opgezet in Hamburg, Frankfurt en andere Duitse steden. In 1815 begon de beurs van Hamburg met het verhandelen van bedrijfsaandelen, wat een belangrijk moment was in de ontwikkeling van Duitsland naar een moderne kapitalistische economie. De Duitse aandelenmarkten bleven actief tot de Nationaal Socialistische Partij onder leiding van Adolf Hitler in 1933 aan de macht kwam. Vervolgens werden alle bedrijven gedwongen om zich bij kartels aan te sluiten en kwam hun kapitaal onder controle van het naziregime.

De *Deutsche Börse Group* beschrijft deze episode als volgt: "Met de machtsovername door de nazis in 1933 werd het algemene economische beleid opgenomen in het algemene regerings- en oorlogsbeleid. Het toezicht op de beurzen werd weggehaald bij de deelstaten en werd het domein van de centrale overheid, waarbij het aantal beurzen werd teruggebracht van 21 naar 9. De beurs van Frankfurt nam de beurs van Mannheim in 1935 over. De gefuseerde instelling werd de Rijn-Main Beurs genoemd. Hoewel de beurs van Frankfurt bleef functioneren als een binnenlandse beurs, had het in werkelijkheid geen belangrijke functie. De economische controle van de nazis beperkte de ontwikkeling van de vrije markt en de aandelenhandel. Over het algemeen werd gedacht dat potentiële kapitaalgoederen alleen ten goede kwamen aan de oorlogseconomie en niet langer konden worden geïnvesteerd in grotere obligaties of aandelen."[@132]

Na de val van het naziregime ontwikkelde het westen van Duitsland zich tot een kapitalistische economie, waarbij de aandelenbeurzen weer als een vrije markt gingen functioneren. Het oosten van het land behield daarentegen een socialistische economie en kende geen werkende beurzen tot aan de Duitse hereniging in 1990.

Polen dient eveneens als een leerzaam voorbeeld. De eerste Poolse beurs werd opgericht in 1817 en begon in de jaren 1840 met de handel in bedrijfsaandelen. Deze beurs bleef operationeel tot 1915, toen deze sloot vanwege de ineenstorting van de Poolse economie tijdens de Eerste Wereldoorlog. In 1919 werd de beurs opnieuw geopend, waarmee Polen terugkeerde naar een kapitalistische economie, tot het land in 1939 gezamenlijk werd binnengevallen door de nazi-sovjetalliantie en de controle werd verdeeld tussen Duitsland en Rusland. Na de nederlaag van de nazi's in 1945, kwam geheel Polen, nog steeds zonder functionerende beurs, onder controle van de Sovjet-Unie. Dit leidde het land naar socialistische armoede en economisch falen tot 1991, toen het socialistische economische systeem van Polen instortte en een vrijemarkteconomie werd ingevoerd. In april 1991 werd de aandelenmarkt opnieuw geopend.[@133]

In alle drie de genoemde landen fungeert het bestaan van een aandelenmarkt als een betrouwbare indicator voor de economische transitie tussen pre-kapitalistische, kapitalistische en socialistische vormen van economische organisatie. Het is geen toeval dat in deze landen de periodes zonder aandelenmarkt samenvielen met armoede, oorlog en omvangrijke vernietiging van kapitaalmiddelen.

Tegenwoordig is het een veelvoorkomend verschijnsel dat politici, vooral in de Verenigde Staten en in ontwikkelingslanden, Scandinavische landen aanhalen als voorbeelden van succesvolle socialistische regimes. Echter, de beurzen in alle Scandinavische landen zijn al meer dan een eeuw onafgebroken operationeel. De Deense beurs is actief sinds 1808, de Zweedse sinds 1863, de Noorse sinds 1881, en de Finse sinds 1912.[@134] Geen van de Scandinavische aandelenmarkten is ooit overgenomen door een regering, wat betekent dat de verdeling van eigendom en kapitaal in al deze economieën altijd is geleid door de voorkeuren en acties van vrij handelende individuen, en niet door dwingende opdrachten van een centrale overheidsinstantie. In tegenstelling tot de vaak onsamenhangende en emotioneel geladen publieke discussies over dit thema, biedt Mises heldere criteria om te bepalen wat een socialistisch economisch systeem inhoudt.

## Kapitalisme is ondernemend, niet bureaucratisch

Het belang van privaat eigendom van productiemiddelen voor het economische systeem wordt duidelijk in, en geïllustreerd door, Mises' uitleg van het kapitalisme als een ondernemend systeem, in tegenstelling tot een bureaucratisch systeem. De verwarring rond dit subtiele onderscheid ligt aan de basis van alle pogingen om de markteconomie opzij te zetten ten gunste van centrale planning. In een kapitalistische economie manifesteert de arbeidsdeling zich in het investeringsproces zelf, dat verdeeld is over drie verschillende rollen: de kapitalist, de ondernemer en de manager. Het proces start met de kapitalist, die kiest om consumptie uit te stellen en in plaats daarvan te sparen en later te investeren. In een moderne kapitalistische economie kan de investeerder zijn geld op de financiële markten plaatsen, waarbij het verspreid wordt over verschillende productielijnen en bedrijven. De investeerder kan zelf besluiten waar het geld naartoe gaat, of hij kan deze taak overlaten aan een professionele investeerder die het kapitaal over verschillende economische doelen verdeelt. Deze allocatie van kapitaal is de ondernemersfunctie binnen de markten. Nadat het geld is verdeeld over verschillende bedrijven, is het aan de managers van deze ondernemingen om het te gebruiken voor de productie van eindgoederen en diensten. Door de scheiding van eigendom, allocatie en beheer, kan het kapitalistische systeem grote hoeveelheden kapitaal van spaarders uit de hele samenleving mobiliseren. Spaarders kunnen zich specialiseren in hun eigen vakgebied zonder zich zorgen te maken over de allocatie van kapitaal of het management ervan.

Een vrije markt voor kapitaalgoederen zorgt ervoor dat elke bezitter van kapitaal dit productief moet inzetten of het risico loopt het te verliezen aan degenen die het wel productief kunnen gebruiken. De rol van financiële markten en hun talrijke financiële instrumenten is om vermogen te kanaliseren van degenen die bereid zijn om hun spaargeld te riskeren, namelijk de kapitalisten, naar ondernemers. Deze ondernemers gebruiken hun inschattingsvermogen om het kapitaal zodanig te alloceren dat de hoogst mogelijke productiviteit wordt behaald. Op hun beurt vertrouwen deze ondernemers investeringen toe aan professionele managers. Deze managers zijn gespecialiseerd in het productief inzetten van kapitaal en arbeid.

Hoe belangrijk de rol van de manager ook mag zijn, deze is duidelijk gescheiden van de functie van de kapitalist, die het kapitaal levert, en van de ondernemer, die beslist over de toewijzing ervan. Deze rollen kunnen in bepaalde situaties weliswaar door dezelfde persoon vervuld worden, maar ze blijven inhoudelijk verschillend. De ondernemer houdt zich bezig met economische calculaties op de kapitaalmarkten en kiest de meest productieve manier voor het inzetten van kapitaal. De manager daarentegen maakt economische berekeningen met de reeds ingezette kapitaalgoederen en beslist over de meest effectieve inzet ervan binnen de productielijn die door de ondernemer is uitgekozen.

De functie van de ondernemer in een markteconomie is om de allocatie van kapitaal aan verschillende productielijnen en verschillende bedrijfstakken te bepalen. De ondernemer beslist welke producten hij wil produceren en welke productielijnen geïntroduceerd, uitgebreid, afgeschaald of gesloten moeten worden. Zodra deze fundamenten zijn gelegd, vertrouwt de ondernemer het toezicht op het dagelijks verloop van deze productieprocessen toe aan de manager. De manager is niet verantwoordelijk voor de allocatie van kapitaal aan productieprocessen, maar beheert het slechts zodra het eenmaal is toegewezen. Zoals Mises stelde: "Zij die ondernemerschap en management met elkaar verwarren sluiten hun ogen voor het economische probleem. ...  Het kapitalistische systeem is geen managementsysteem; het is een ondernemend systeem."[@135] Voor academici en geleerden die nooit betrokken zijn geweest bij ondernemerschap is dit onderscheid niet duidelijk, wat resulteert in hun geloof dat privaat eigendom van kapitaal kan worden ingeperkt zonder het productieproces te beïnvloeden, omdat in hun modellen de werknemers en managers het hele productieproces aankunnen, de kapitalisten niets bijdragen en de ondernemer een onbelangrijk detail is.

Maar in de echte wereld worden de acties van management en arbeid bepaald en gedicteerd door de allocatie van kapitaal door ondernemers. De juiste kosten en baten van handelingen kunnen niet worden berekend tenzij de kapitaalgoederen in kwestie eigendom zijn van iemand die ze kan gebruiken zoals hij wil. Als alle opties beschikbaar zijn voor de eigenaar, kan deze de optie kiezen die de samenleving het beste dient en die hem de meeste winst oplevert. Zonder volledige controle over kapitaalgoederen en eigendom hiervan, wat inhoudt dat er winst wordt gemaakt en verlies wordt geleden, is er geen ruimte voor een rationele calculatie van winst en verlies.

## Winst en verlies

Ondernemers speculeren op winstgevende productieprocessen en zetten de productiefactoren (arbeid, kapitaal en land) hier op in. Ze maken de opstartkosten, nemen de risicos en innen vervolgens de opbrengsten en beloningen. Het gebruik van geld als ruilmiddel betekent dat het de helft uitmaakt van elke economische transactie in een markteconomie; hierdoor kan geld dienen als hulpmiddel voor ondernemers om winsten en verliezen te berekenen door al hun kosten en inkomsten in hetzelfde ruilmiddel uit te drukken. Wanneer ondernemers berekenen dat hun inkomsten in een bepaalde branche hoger zijn dan hun uitgaven, beseffen ze dat ze winst maken. Deze winst impliceert dat de marktwaardering voor alle omzet die de ondernemer realiseert, hoger is dan de marktwaardering voor alle uitgaven die hij heeft gebruikt als inputs voor het productieproces. De subjectieve waardering van andere marktdeelnemers voor de output van het productieproces is groter dan de waardering voor de input. Door winst te maken dienen ondernemers de maatschappij. Arbeid, land, kapitaal, en grondstoffen worden in het productieproces omgezet in eindproducten die door de samenleving hoger gewaardeerd worden. Als beloning voor deze waardecreatie ontvangen de betrokkenen winst. Dit stelt hen in staat om meer te ondernemen en met grotere middelen te opereren.

Wanneer het inkomen van een ondernemer lager uitvalt dan zijn uitgaven, maakt hij verlies. Dit komt doordat de gangbare marktprijs van zijn input hoger ligt dan de prijs die hij ontvangt voor zijn output, of productie. In dit geval heeft de ondernemer schaarse en waardevolle middelen omgezet in minder waardevolle eindproducten, waardoor hij in feite de samenleving om zich heen verarmt. Dit verlies vermindert het kapitaal waarover hij beschikt en dwingt hem om zijn productiemethoden aan te passen, over te stappen op andere bedrijfsactiviteiten, of zelfs om te stoppen als ondernemer. De scorekaart in het spel van het kapitalisme is het eigen vermogen en de welvaart van de ondernemer, en zonder deze zeer persoonlijke en onverbiddelijke betrokkenheid kan er geen rationele berekening zijn van het beste gebruik van kapitaal en geen marktproces om er voortdurend voor te zorgen dat kapitaal wordt beheerd door de meest bekwame. Economen die denken dat marktproductie kan worden nagebootst zonder privaat eigendom, winst en verlies, houden zich bezig met pseudowetenschap, zoals primitieve stammen die voor het eerst vliegtuigen zagen en zich voorstelden dat het nabootsen van hun vorm met houten stokjes een functionerend vliegtuig zou opleveren.

De discussie over schaarste in de eerste hoofdstukken van het boek is essentieel om te begrijpen waarom economische calculatie alleen kan werken in de context van private eigendomsrechten. Tenzij de persoon die alloceert echte keuzes moet maken waarbij verschillende opties voor schaarse middelen tegen elkaar worden afgewogen, zal hij niet in staat zijn om de werkelijke kosten in overweging te nemen. Kapitalisme werkt juist omdat er voor de deelnemers altijd veel op het spel staat: "Speculeren en investeren is geen spelletje. De speculanten en investeerders stellen hun eigen vermogen, hun eigen lot op het spel. Dit feit maakt hen verantwoordelijk tegenover de consumenten, de uiteindelijke bazen van de kapitalistische economie. Als men hen van deze verantwoordelijkheid ontslaat, ontneemt men hen ook hun eigenlijke karakter."[@136] Dit is het proces van economische berekening en het is de essentiële rol van de ondernemer. Een van Mises meest blijvende en significante bijdragen is de uiteenzetting van de centrale rol van het calculatieproces in een kapitalistische economie.

## Het probleem van economische calculatie

Wanneer we het falen van socialistische economische systemen bespreken, wijzen veel leken en hedendaagse economen vaak op het probleem van stimulansen. In een systeem waar eigendomsrechten beperkt zijn en beloningen door centrale planners worden vastgesteld, bestaat er weinig financiële prikkel om uit te blinken in je werk. Ook is er weinig motivatie om onaangenaam en moeilijk werk te verrichten. Als iedereen een vergelijkbare levensstandaard heeft, waarom zou iemand dan kiezen voor het ophalen van vuilnis of het vele jaren trainen om hersenchirurg te worden? En waarom zou men überhaupt werken als de overheid een fatsoenlijk inkomen garandeert? Hoewel dit zeker een uitdaging vormt voor socialistische economieën, vertegenwoordigt het niet het kernprobleem van socialisme op economisch vlak. Vele socialistische regimes hebben de stimuleringsproblematiek opgelost door middel van dwang: weigering om vuilnis buiten te zetten of bevelen te volgen kan resulteren in de dood of deportatie naar werkkampen. De dreiging van de dood of ernstige straf is voor veel mensen een krachtigere motivatie dan de wens om rijk te worden. Rapporten over de ondergang van socialistische economieën tonen aan dat het probleem niet zozeer ligt bij de afwezigheid van werkwilligheid. Gevangenen in de goelags hadden geen andere keus dan op te dagen, en veel werknemers gingen naar hun reguliere werk uit vrees voor de goelags. Desondanks faalden socialistische regimes alsnog.

Mises gaat zelfs nog verder. Hij stelt dat zelfs als de socialisten erin geslaagd waren om een samenleving op te bouwen die volledig bestond uit de mythische, nieuwe socialistische mens, die volkomen onbaatzuchtig was in zijn toewijding aan de zaak, het socialisme nog steeds zou falen. Zoals Rothbard stelt: "Wat zouden die centrale planners dit leger precies vertellen om te doen? Hoe zouden ze weten welke producten ze hun gewillige slaven moeten laten produceren, in welk stadium van de productie, hoeveel van het product in elk stadium, welke technieken of grondstoffen ze moeten gebruiken in die productie en hoeveel van elk, en waar ze al deze productie precies moeten plaatsen? Hoe zouden ze weten wat hun kosten zijn, of welk productieproces wel of niet efficiënt is?"[@137]

In zijn analyse van het socialisme in 1922, toen de meeste economen onder de indruk waren van dit populaire nieuwe idee dat rond de wereld reisde, identificeerde Mises terecht de achilleshiel van socialistische economische systemen als het onvermogen om berekeningen uit te voeren om kapitaalgoederen te alloceren zonder rekening te houden met de bijbehorende private eigendomsrechten. Er is geen rationele manier om vast te stellen hoe middelen moeten worden gealloceerd zonder eigendom, prijzen en een markt voor ondernemers en consumenten om economische calculatie te verrichten. Om Rothbard te citeren:

::: blockquotebox
Mises toonde aan dat, in elke economie die complexer is dan het niveau van Crusoë of een primitief huishouden, het socialistische centraal planbureau eenvoudigweg niet zou weten wat te doen, of hoe deze cruciale vragen te beantwoorden. Mises ontwikkelde het memorabele concept van calculatie en wees erop dat het planbureau deze vragen niet kon beantwoorden omdat het socialisme het onmisbare gereedschap zou missen dat particuliere ondernemers gebruiken om te schatten en te calculeren: het bestaan van een markt voor de productiemiddelen, een markt die geldprijzen tot stand brengt gebaseerd op ruilhandel met winstbejag door particuliere eigenaren van deze productiemiddelen. Aangezien de essentie van het socialisme collectief eigendom van de productiemiddelen is, zou het planbureau niet in staat zijn om te plannen of om enige vorm van rationele economische beslissingen te nemen. Zijn beslissingen zouden noodzakelijkerwijs volledig willekeurig en chaotisch zijn en daarom is het bestaan van een socialistische planeconomie letterlijk "onmogelijk".

...

Mises concludeert dat in de socialistische economie "in plaats van de economie van de anarchistische productiemethode, een beroep zal worden gedaan op de zinloze productie van een absurde machine. De tandwielen zullen draaien, maar zonder resultaat."
:::

[@138]

Hoe kunnen planbureaus bepalen of hun staal beter ingezet kan worden voor de productie van auto's of treinen? Zonder een markt voor auto's of treinen, waar deze door de overheid aan burgers worden toegewezen, missen planners een mechanisme om te beoordelen hoeveel waarde burgers toekennen aan auto's ten opzichte van treinen. Hoe zou een centrale planner dan de allocatie moeten vaststellen? In een marktsysteem maken consumenten de keuze tussen het kopen van auto's en treinkaartjes op basis van hun persoonlijke voorkeuren, en ontvangen de producenten van zowel auto's als treinen geld. Dit geld kunnen zij vervolgens gebruiken om te bieden op kapitaalgoederen. De hoogste bieder, oftewel de kapitalist die de middelen het meest productief kan inzetten, krijgt het staal. Zo wordt het staal gealloceerd daar waar het het hardst nodig is.

Verschillende socialistische economen (excuseer me voor het gebruik van dit oxymoron) erkenden de kritiek van Mises en pasten hun economische systemen aan in een poging deze kritiek te weerleggen. Zij stapten af van het naïeve geloof dat het onteigenen van kapitaal van eigenaren automatisch zou leiden tot de productie van onbeperkte hoeveelheden goederen, genoeg voor iedereen om te nemen wat ze nodig hadden. Ook lieten ze het idee van een economie zonder geld of prijzen, of een economie waarin prijzen worden vastgesteld op basis van de arbeidswaardetheorie, achter zich. In plaats daarvan stelden socialisten zoals Oskar Lange, Abba Lerner en Fred Taylor voor dat het centrale planbureau opdrachten zou geven aan managers om prijzen toe te wijzen aan goederen, de reacties van kopers te observeren en via *trial-and-error* de juiste prijzen te bepalen, op dezelfde manier zoals kapitalisten dat zouden doen. Ze zouden reageren op een overschot door de prijs te verlagen en op een tekort door de prijs te verhogen. Met deze truc hoopten de socialistische centrale planners een cruciaal aspect van de markteconomie te simuleren, en de uitvoering van hun socialistische plannen te waarborgen.

Lange was een Poolse socialistische econoom en vriend van Jozef Stalin, wiens onbezonnen plannen aan de basis lagen van de vernietiging van de Poolse economie. Terwijl hij de kritiek van Mises in zich opnam en geloofde dat hij het socialisme eraan had aangepast, schreef hij zelfs over de dankbaarheid die de toekomstige socialistische utopie aan Mises verschuldigd zou zijn, omdat hij de enige persoon was die de aandacht vestigde op de belangrijkste elementen van een markteconomie dat door hun kinderachtige model genegeerd werd.

::: blockquotebox
Socialisten hebben zeker een goede reden om professor Mises, de grote advocatus diaboli van hun ideeën, dankbaar te zijn. Want het was zijn krachtige uitdaging die socialisten dwong om het belang te erkennen van een adequaat systeem van economische boekhouding ... de verdienste van het feit dat hij de socialisten ertoe heeft gebracht om dit probleem systematisch te benaderen behoort volledig toe aan professor Mises.
:::

[@139]

De socialistische loskoppeling van de werkelijkheid ging zo ver dat Lange voorstelde om een standbeeld van Mises te bouwen in het centraal planbureau van de succesvolle socialistische staat! Helaas hadden de socialisten niet geleerd van de lessen van Mises, anders waren ze niet op zo'n komische manier zeker geweest van hun nakend succes. De managers van de socialistische centrale planners waren geen ondernemers. Ze konden de winsten en verliezen van verschillende productielijnen niet berekenen. Zelfs als ze een markt hadden voor consumptiegoederen, zou de overheid eigenaar blijven van de kapitaalgoederen, want dat is de definitie van socialisme. Een rationele economische calculatie kan niet puur op basis van een markt in eindproducten plaatsvinden. Kapitalisten moeten met concurrenten op kapitaal bieden om de meest productieve toepassingen ervan naar voren te laten komen, waarbij de succesvolle kapitalisten en ondernemers worden beloond met meer kapitaal en de onsuccesvolle worden bestraft met minder kapitaal. Als al het kapitaal in handen is van één entiteit, en die entiteit wijst het toe zonder gebruik te maken van marktprijzen en berekeningen van winst en verlies als leidraad, dan kan kapitaal niet rationeel worden toegewezen. Mises concludeert:

::: blockquotebox
Maar het kenmerkende van het socialistische systeem is dat de goederen van de producenten gecontroleerd worden door slechts één instantie in wiens naam de directeur handelt, dat ze noch gekocht, noch verkocht worden en dat er geen prijzen voor zijn. Er kan dus geen sprake zijn van het vergelijken van input en productie door middel van rekenkundige methoden.
:::

[@140]

Socialisten hebben geprobeerd om diverse aanpassingen aan hun systeem te maken om de fundamentele fout die Mises identificeerde, aan te pakken. Een dergelijke poging was het gebruik van consumentenenquêtes om inzicht te krijgen in de wensen van mensen, met de bedoeling om de beslissingen van planners te informeren. Echter, abstracte enquêtevragen kunnen marktbeslissingen, die gebaseerd zijn op werkelijke prijzen en schaarste, niet vervangen. Wanneer mensen wordt gevraagd naar welke auto ze het liefst zouden willen hebben, zullen ze waarschijnlijk kiezen voor Ferrari's, Lamborghini's en modellen van andere dure autofabrikanten. Maar in werkelijkheid kiest de overgrote meerderheid van de mensen voor Toyota's, Honda's, Kia's, en andere betaalbare opties die binnen hun behoeften en budgettaire beperkingen passen. Zonder het concept van opportuniteitskosten zijn wensen onbegrensd en bestaan er geen afwegingen.

Het idee dat marktallocatie kan worden gerealiseerd door managers het kapitaal onder hun gezag te laten behandelen alsof het hun eigendom is en consumenten hun voorkeuren te laten uiten in enquêtes is zo absurd dat het alleen dient om het volslagen gebrek aan begrip aan te tonen van wat een markteconomie is en hoe zij functioneert. Economische beslissingen worden alleen genomen in de context van schaarste, wanneer elke beslissing reële kosten en baten met zich meebrengt die de beslisser in de echte wereld zal ervaren. Zonder eigendom, opportuniteitskosten en gevolgen in het echte leven lijken socialistische schijnmarkten in niets op de echte. Zoals Mises het zegt:

::: blockquotebox
Wat deze neosocialisten voorstellen is eigenlijk paradoxaal. Ze willen de particuliere controle over de productiemiddelen, ruilhandel, marktprijzen en concurrentie afschaffen. Tegelijkertijd willen ze de socialistische utopie op zo'n manier organiseren dat mensen kunnen doen alsof deze dingen er nog steeds zijn. Ze willen dat mensen de markt spelen op dezelfde manier waarop kinderen oorlogje, treinmachinist of schooltje spelen. Ze begrijpen niet hoe zon kinderachtig spel verschilt van wat het probeert na te bootsen.
:::

[@141]

## Moderne economie en calculatie

Het idee dat centrale planners economische calculatie zouden kunnen verrichten zonder rekening te houden met privaat eigendom is ook onhoudbaar wanneer men de dynamische en steeds veranderende aard van een markteconomie begrijpt. De allocatie van middelen en kapitaal voor productie is geen eenmalige beslissing die centrale planners één keer goed moeten doen, zodat hun economie op de automatische piloot kan draaien. De wereld is dynamisch en verandert voortdurend, ondernemers ontdekken continu nieuwe manieren om producten te maken en consumenten ontdekken voortdurend nieuwe voorkeuren voor nieuwe producten. Onzekerheid is altijd aanwezig. De kapitalistische ondernemer is de belangrijkste speler in het economische systeem, omdat hij zijn eigendom inzet op zijn vermogen om correct te anticiperen op veranderingen. Hij is de kracht die veranderingen beïnvloedt en de economische realiteit creëert. De algemene evenwichtsmodellen van de moderne economie zijn in wezen waardeloos omdat ze geen ruimte bieden aan de rol van de ondernemer. Deze modellen nemen de economische realiteit zoals het is, negeren hoe het tot stand is gekomen en laten geen ruimte voor het proces dat het onvermijdelijk zal veranderen.

Verbazingwekkend genoeg hebben moderne mainstream economen de kritiek van Mises op het socialisme volledig genegeerd. Ze blijven werken binnen het domein van de Walrasiaanse algemene evenwichtsmodellen voor economische activiteit. Dit type literatuur zou eerder thuishoren in de fictieafdeling dan in het gedeelte van de bibliotheek dat gereserveerd is voor economie. Binnen dit kader van economische fictie zijn alle economische data bekend bij alle marktdeelnemers. Dit gaat van smaken en waardeschalen tot technologieën en beschikbare middelen; er bestaat een toestand van perfecte concurrentie tussen de producenten; en alle managers beschikken over volledige kennis van alle prijzen. Er zijn geen ondernemers in de zin van Mises, alleen managers, en de allocatie van kapitaal wordt als een vast gegeven gezien. Socialistische en Keynesiaanse economen zijn van mening dat centrale economische planning kan werken in zo'n statische en totaal onrealistische wereld. In plaats van deze benadering van de economie fundamenteel in vraag te stellen, vinden economen op de een of andere manier redenen om het socialisme te verheerlijken in deze volkomen absurde modellen.

Algemeen evenwicht is een concept dat abstraheert van de echte wereld zodat we die kunnen analyseren. Het is puur theoretisch. Natuurlijk is calculatie door een centrale planner in het theoretische algemene evenwichtsmodel mogelijk; daar zijn deze modellen voor gemaakt. Maar dat vertaalt zich niet naar de calculatie in de realiteit, omdat de echte wereld heel anders is dan de theorie. In de poging om hun irrelevante en simplistische modellen op de werkelijkheid te projecteren, lijken moderne economen op navigators die rond een wereldkaart lopen en concluderen dat ze in dezelfde tijd rond het gebied op de kaart kunnen lopen als de tijd die het hen kost om rond de kaart zelf te lopen.

Alleen als je de absurditeit van het fetisjisme rond de algemene evenwichtstheorie van Walras begrijpt, kun je het hilarische en schandalige gedrag begrijpen van de moderne westerse economen die de economie van de Sovjet-Unie prijzen. Paul Samuelson schreef het populairste economische leerboek van de twintigste eeuw, dat is gebruikt om miljoenen over de hele wereld te doen geloven in een verwarrende socialistisch-Keynesiaanse mengelmoes. De verbazingwekkende details zijn te vinden in "Soviet Growth and American Textbooks", een artikel van David Levy en Sandra Peart.[@142] Levy en Peart onderzochten de verschillende versies van Samuelsons leerboek en ontdekten dat hij herhaaldelijk het economische model van de Sovjet-Unie presenteerde als zijnde bevorderlijker voor economische groei. In de vierde editie uit 1961 voorspelde hij dat de economie van de Sovjet-Unie die van de Verenigde Staten ergens tussen 1984 en 1997 zou inhalen. Deze voorspellingen dat de Sovjets de Verenigde Staten zouden inhalen, werden met toenemend vertrouwen voortgezet in zeven edities van het leerboek, tot de elfde editie in 1980, met wisselende schattingen van wanneer de inhaalslag zou plaatsvinden. In de dertiende editie die in 1989 is gepubliceerd en die op de bureaus van universiteitsstudenten terechtkwam toen de Sovjet-Unie uiteen begon te vallen, schrijven Samuelson en zijn toenmalige co-auteur William Nordhaus: "De Sovjeteconomie is het bewijs dat, in tegenstelling tot wat veel sceptici eerder hadden geloofd, een socialistische geleide economie kan functioneren en zelfs kan gedijen."[@143] Dit was ook niet beperkt tot één leerboek, want Levy en Peart laten zien dat dergelijke inzichten gebruikelijk waren in de vele edities van wat waarschijnlijk het op één na populairste economie leerboek is, *McConnells Economics: Principles, Problems and Policies* en verschillende andere leerboeken.[@144] Elke universiteitsstudent die na de oorlog economie studeerde volgens een Amerikaans curriculum, wat voor de meerderheid van de studenten wereldwijd het geval was, leerde dat het Sovjetmodel een efficiëntere manier van economische organisatie vormde. Zelfs na de ineenstorting en de totale mislukking van de Sovjet-Unie bleven dezelfde leerboeken in gebruik op dezelfde universiteiten. De nieuwere edities schrapten weliswaar de overdreven positieve uitspraken over het succes van het Sovjetmodel, maar ze stelden het onderliggende economische wereldbeeld en de methodologische benaderingen niet ter discussie.[@145]

## De gevolgen van ondernemend investeren

Economische calculatie in een door ondernemers geleide markteconomie heeft verschillende belangrijke economische gevolgen. De meest voor de hand liggende en opmerkelijke is dat zij de productiviteit van kapitaalinvesteringen verhoogt. Ondernemerschap brengt de voordelen van specialisatie en arbeidsdeling in het proces van kapitaalallocatie. Het stelt spaarders in staat om kapitalisten te worden door de ondernemende en bestuurlijke functies van het kapitalisme aan anderen te delegeren, waardoor sparen en investeren meer worden aangemoedigd en de rentevoeten worden verlaagd. Deze toename in sparen en investeren resulteert in een verlenging van de productieprocessen, doordat kapitaal voor steeds langere perioden beschikbaar blijft. Meer kapitaal stimuleert uitvindingen en innovatie, waardoor het aanbod van goederen en diensten voor alle marktdeelnemers toeneemt. Economische calculatie in investeringen van ondernemers leidt ook tot een verhoogde productiviteit voor investeringen door voortdurend de meest productieve te belonen en de minst productieve af te straffen.

De voordelen van kapitalistisch ondernemerschap in een marktorde reiken verder dan alleen de ondernemer en de investeerder. Kapitalistisch ondernemerschap leidt tot aanhoudende stijgingen van de reële lonen, omdat meer kapitaal en een efficiëntere kapitaalallocatie de arbeidsproductiviteit verhogen. Hoewel de lonen in reële termen zullen stijgen, zullen ze op de lange termijn waarschijnlijk in nominale termen dalen, omdat de toegenomen productie van alle goederen waarschijnlijk zal leiden tot een daling van hun nominale prijzen, vergeleken met de waarde van geld, zijnde het goed wat de markt selecteert als het goed dat het moeilijkst te produceren is.

Ondernemers en kapitalisten maken door hun ondernemerschap winst, maar deze winsten zijn over het algemeen onzeker, omdat ze onderhevig zijn aan concurrentie van andere ondernemers die de prijs van productiefactoren kunnen opdrijven. Kapitalisten profiteren niet noodzakelijk van de accumulatie van kapitaal, die, zoals besproken in Hoofdstuk 6, gepaard gaat met hoge kosten. Er is altijd een risico op verlies. En als er winst is, zal de markt die snel beginnen op te slokken. Hogere winsten zullen onvermijdelijk naar de werknemers en landeigenaren gaan, wiens lonen en huurprijzen zullen blijven stijgen in overeenstemming met hun toenemende productiviteit. Ondernemen is niet alleen maar "plezier en vertier"; het brengt veel meer onzekerheid met zich mee dan arbeid. Het is volkomen begrijpelijk dat een groot aantal mensen arbeid verkiest boven ondernemerschap. Arbeid in een grote markt met een zeer productieve arbeidsdeling kan heel lonend zijn en brengt veel minder risico met zich mee.

Naast de economische voordelen van kapitalisme is de sociale implicatie van kapitalisme dat het gedrag stimuleert dat bevorderlijk is voor een vreedzame samenleving. Als je je op een beschaafde manier kunt gedragen, kun je deelnemen aan economische netwerken met een groeiend aantal mensen en een hoge mate van specialisatie.
