# Tijdsvoorkeur {#sec-tijdsvoorkeur}

::: blockquotebox
Ongeacht de oorspronkelijke tijdsvoorkeur van een individu of de oorspronkelijke verdeling van deze tijdsvoorkeur binnen een bepaalde bevolking, geldt dat zodra deze tijdsvoorkeur laag genoeg is om spaargeld, kapitaal of duurzame consumptiegoederen mogelijk te maken, een tendens naar een lagere tijdsvoorkeur in gang wordt gezet, wat gepaard gaat met een 'beschavingsproces'.

--- Hans-Hermann Hoppe[@146]
:::

In Hoofdstuk 10 werd het concept van geld uitgelegd, maar in dit hoofdstuk en de volgende twee hoofdstukken wordt dieper ingegaan op de werking van geld in een kapitalistische markteconomie, die werd besproken in de Hoofdstukken 11 en 12. Dit hoofdstuk begint met een uitleg over tijdsvoorkeur en de rol die het heeft bij het bepalen van rentetarieven op de markt. Het volgende hoofdstuk introduceert het onderwerp bankieren, en Hoofdstuk 15 legt uit hoe de verstoring van de geldmarkt leidt tot een conjunctuurcyclus. Dit is een uiterst belangrijk onderwerp in de economie, omdat je de economische rampen die de wereld de afgelopen eeuw hebben getroffen alleen kunt begrijpen als een gevolg van de verstoring van de markt voor geld en kapitaal. Het gangbare door de staat gesponsord economieboek beschouwt economische rampen als een normaal, onvermijdelijk en onverklaarbaar onderdeel van het marktproces. In deze visie is de conjunctuurcyclus net als het weer of een onvermijdelijke natuurramp die door centrale overheden moet worden bijgestuurd en getemperd door verstandig fiscaal en monetair beleid. De nauw verwante marxistische economen zien het economisch falen als het onvermijdelijke gevolg van een kapitalistisch economisch systeem en de voorwaarde van de onvermijdelijke opstand van arbeiders tegen het kapitalisme.

Maar door de economische manier van denken en de instrumenten van economische analyse toe te passen op de kwestie van geld, kan worden verklaard hoe en waarom crises plaatsvinden, hoe ze kunnen worden vermeden en wat de problemen zijn van de door de staat gesponsorde economieboeken. Misschien zijn de implicaties van de Oostenrijkse methode op geen enkel gebied van economische analyse zo relevant als bij dit onderwerp. De reden dat de Oostenrijkers zo belasterd en buitengesloten worden van de mainstream academische wereld is niet omdat hun ideeën er flagrant naast zitten. Het is omdat ze een samenhangende verklaring bieden voor het ontstaan van geld op de vrije markt en van de verwoestende gevolgen wanneer deze enorm belangrijke technologie aan de heerschappij van overheidsmonopolie wordt overgelaten. Geld kan bestaan zonder overheid en het is mogelijk om het onderwerp geld te onderzoeken zonder terug te vallen op het belachelijke quasi-religieuze geloof dat moderne economische leerboeken stellen in de almachtige en alwetende monetaire centrale planners. De Oostenrijkers worden verguisd omdat hun grondige kennis van de economie een bedreiging vormt voor iedereen die baat heeft bij sterke centrale overheden die het geld beheren.

Voor het grootste deel van haar geschiedenis heeft de Oostenrijkse School haar theorieën moeten uitleggen op de manier die door door de staat gesponsorde economen was opgelegd. Dit boek benadert de kwestie van geld vanuit het perspectief van de Oostenrijkse School zelf en bouwt de zaak op vanuit de grondbeginselen. Om geld als een marktverschijnsel te kunnen verklaren, moeten we de analyse beginnen vanuit het begrip van tijdsvoorkeur. De schaarste van tijd is het uitgangspunt voor alle economische keuzes. De schaarste van tijd dwingt de mens om op alle momenten in zijn leven te kiezen tussen alternatieven. Dit wil zeggen dat elke beslissing opportuniteitskosten met zich meebrengt. Zelfs zonder beperking op de hoeveelheid beschikbare middelen, resulteert de keuze van een individu om zijn tijd te besteden in het afstrepen van alle andere keuzes waarvoor hij diezelfde tijd had kunnen gebruiken.

Tijd economisch afwegen is uniek omdat tijd verstrijkt en niet gestopt of teruggedraaid kan worden. Wanneer de mens wordt geboren, begint zijn levensklok onophoudelijk te tikken en deze stopt pas wanneer hij sterft. Je weet niet wanneer deze klok zal stoppen en je kunt hem niet opnieuw starten nadat hij is gestopt. De mens krijgt één ononderbroken kans om te leven en hij weet niet wanneer die zal eindigen.

Tijd is geen normaal goed waarvan de mens de gewenste hoeveelheid kan kiezen. Er is geen keuze op de markt mogelijk tussen verschillende hoeveelheden tijd en tijd kan niet rechtstreeks worden verhandeld. De manier waarop een individu tijd waardeert, is subjectief en variabel, maar er bestaan enkele constanten. Hoe dichter een tijdspanne bij het heden ligt, hoe waardevoller die voor een individu lijkt. Het heden is zeker, omdat het er al is, maar de toekomst is altijd onzeker, omdat die misschien nooit komt. Men kan alleen in de toekomst terechtkomen door te overleven in het heden, waardoor de behoeften van het heden altijd dringender en belangrijker zijn. Het heden is het moment waarop alle zintuigen het geluk en de pijn van het leven ervaren. Toekomstige pijn en plezier zijn hypothetisch, maar die van het heden zijn echt en je voelt het. Honger in het heden is veel dringender dan honger in de toekomst, waardoor voedsel in het heden waardevoller is dan in de toekomst. Gevaar in het heden is veel dringender dan gevaar in de toekomst, en middelen die vandaag veiligheid bieden zijn daarom vandaag waardevoller dan in de toekomst. Als de mens de keuze heeft tussen het verkrijgen van een fysiek goed in het heden of hetzelfde goed in de toekomst, dan kiest hij voor het heden.

De hogere waardering van goederen in het heden is een vast gegeven van menselijk handelen. Het feit dat mensen ervoor kiezen om te consumeren in plaats van alleen maar meer van de goederen op te potten die ze waarderen, zoals geld, bevestigt deze voorkeur. Hun keuze om in het heden te consumeren betekent dat ze een hogere waarde hechten aan een goed in het heden dan aan hetzelfde goed in de toekomst. Tijdsvoorkeur is de mate waarin goederen in het heden worden verkozen boven toekomstige goederen. Het is altijd positief omdat mensen altijd de voorkeur geven aan goederen in het heden boven toekomstige goederen, maar de mate waarin varieert van persoon tot persoon en voor elke persoon tijdens zijn leven, afhankelijk van zijn situatie. Een hoge tijdsvoorkeur duidt op een lagere waardering van de toekomst ten gunste van het heden en een grotere gerichtheid op het heden, terwijl een lage tijdsvoorkeur duidt op een hogere waardering van de toekomst en een grotere gerichtheid op de toekomst.

Een eindeloze verscheidenheid aan factoren kan de tijdsvoorkeur van een individu beïnvloeden. Hoppe maakt onderscheid tussen externe, biologische en sociale of institutionele factoren. Externe gebeurtenissen beïnvloeden de verwachtingen van een individu voor zijn toekomst en ze beïnvloeden zo de mate waarin men prioriteit geeft aan deze toekomst. De biologische realiteit van het leven bepaalt ook de tijdsvoorkeur van een individu. Zoals Hoppe uitlegt:

::: blockquotebox
Het staat vast dat de mens als kind wordt geboren, dat hij opgroeit tot een volwassene, hij zich gedurende een deel van zijn leven kan voortplanten en dat hij ouder wordt en sterft. Deze biologische feiten hebben een directe invloed op tijdsvoorkeur. Vanwege de biologische beperkingen van hun cognitieve ontwikkeling hebben kinderen een extreem hoge tijdsvoorkeur. Ze hebben geen duidelijk concept van een persoonlijke levensverwachting die zich over een lange periode uitstrekt en ze hebben geen volledig begrip van productie als een manier van indirecte consumptie. Als gevolg hiervan genieten goederen in het heden en onmiddellijke voldoening een sterke voorkeur boven toekomstige goederen en uitgestelde voldoening. Sparen en investeren zijn zeldzaam en de productie en bevoorrading voorzien vrijwel alleen in de meest nabije toekomst. Kinderen leven van dag tot dag en van de ene onmiddellijke voldoening naar de volgende. Tijdens het volwassen worden heeft de aanvankelijk extreem hoge tijdsvoorkeur van de mens de neiging om te dalen. Door zijn levensverwachting en de mogelijkheden van productie als middel voor indirecte consumptie te onderkennen, stijgt het marginale nut van toekomstige goederen. Sparen en investeren worden gestimuleerd en productie en bevoorrading worden meer gericht op de langere termijn.

Ten slotte, als je oud wordt en het einde van je leven nadert, zal je tijdsvoorkeur toenemen. Het marginale nut van toekomstige goederen daalt omdat er minder toekomst overblijft. Spaargeld en investeringen zullen afnemen en de consumptie -- inclusief het niet meer aanvullen van kapitaal en duurzame consumptiegoederen -- zal toenemen. Dit ouderdomseffect kan echter worden tegengegaan en opgeschort. Vanwege het biologische feit van voortplanting kan de mens zijn periode van voorzorg verlengen tot voorbij de duur van zijn eigen leven. Als en voor zover dit het geval is, kan zijn tijdsvoorkeur op volwassen niveau blijven tot aan zijn dood.[@147]
:::

Verschillende sociale en institutionele factoren beïnvloeden de tijdsvoorkeur van een individu, waarbij de zekerheid van eigendom wellicht de belangrijkste is. Het hebben van eigendom biedt mensen een effectieve manier om voor hun toekomst te zorgen. Het verwerven van duurzame goederen markeert het begin van een proces waarbij de tijdsvoorkeur van de mensheid afneemt. Een individu dat een waardevol goed bezit dat in de toekomst kan worden gebruikt, vermindert de onzekerheid over zijn toekomst en zal deze waarschijnlijk minder verwaarlozen. Wanneer het concept van eigendomsrechten algemeen wordt aanvaard in een samenleving, zoals besproken in Hoofdstuk 5, leidt dit tot een algemene afname van de tijdsvoorkeur, omdat de toekomst steeds zekerder wordt gewaardeerd. De zekerheid van eigendomsrechten heeft een aanzienlijke invloed op de tijdsvoorkeur. Naarmate de zekerheid van een eigenaar over zijn toekomstige beschikking over een goed toeneemt, zal hij waarschijnlijk het eigendom goed onderhouden en acties ondernemen met het oog op de toekomst.

## Tijdsvoorkeur en geld

Zorg voor de toekomst heeft veel te maken met het samenvallen van behoeften dat in Hoofdstuk 9 in de context van ruilhandel werd besproken. De toekomst is onbekend en onzeker, en niemand kan met zekerheid weten welke goederen hij in de toekomst nodig zal hebben. Net zoals geld het probleem van samenvallende behoeften tijdens ruilhandel oplost, lost het dat ook op voor toekomstige voorzieningen. Door geld te sparen, het meest liquide goed en het algemene ruilmiddel, kunnen spaarders het in de toekomst ruilen voor de meest waardevolle goederen die beschikbaar zijn, en wel op het moment van hun keuze. Geld wordt dus juist aangehouden vanwege onzekerheid. In een toekomst die perfect voorspelbaar is, zouden individuen al hun toekomstige geldstromen rechtstreeks naar de leveranciers van de goederen kunnen laten gaan die ze nodig hebben op het moment dat ze die nodig hebben, en zouden ze geen geld hoeven aan te houden. Maar in de echte wereld, waar de toekomst onvoorspelbaar is, is geld het beste middel om in de toekomst te voorzien, omdat het door zijn liquiditeit kan worden omgezet in alle goederen die in de toekomst gewenst zijn. Als het meest verkoopbare goed kan geld het goedkoopst worden omgezet in het goed dat in de toekomst voor de eigenaar het hoogste marginale nut heeft. Als een goed in de menselijke samenleving zich ontwikkelt tot geld, vinden mensen het een zeer handig en krachtig middel om waarde naar de toekomst door te schuiven, waardoor ze hun tijdsvoorkeur kunnen verlagen en meer kunnen sparen en voor hun toekomst kunnen zorgen. Geld vergroot onze kans om te sparen in plaats van consumptiegoederen voor de lange termijn te bewaren, waarvan het nut in de toekomst onzekerder is en die niet zo makkelijk verkoopbaar zijn.

Naarmate meer mensen geld gebruiken om handel te drijven, wordt de technologie die voor geld wordt gebruikt beter en efficiënter in het uitvoeren van zijn taak als ruilmiddel, zowel in het heden tussen individuen als tussen een huidig individu en zijn toekomstige zelf. Geld is een technologie en de toename van het aantal gebruikers leidt tot een toename van het aantal keuzes die met elkaar concurreren. Betere ideeën en technologieën winnen en verdrijven de inferieure uit de markt. Bij geld heeft de productiviteit van de technologie betrekking op hoe goed het zijn functie als ruilmiddel vervult, of op zijn verkoopbaarheid, zoals besproken in Hoofdstuk 10.

Een monetair middel dat gemakkelijk in enorme hoeveelheden kan worden geproduceerd als reactie op een toenemende vraag, zal op de lange termijn waarschijnlijk te maken krijgen met een aanzienlijke toename van het aanbod en een afname van de economische waarde die erin blijft opgeslagen. Daarentegen zullen monetaire middelen die moeilijk in toenemende hoeveelheden te produceren zijn in reactie op een stijgende vraag, waarschijnlijk hun aanbod in beperkte mate zien toenemen, waardoor hun prijs stijgt om aan de stijgende vraag te voldoen, waardoor ze beter hun waarde behouden. Degenen die hun vermogen opslaan in de hardere valuta zijn getuige van het behoud en de waardestijging van hun vermogen, terwijl degenen die het bewaren in zacht geld waardevermindering ervaren. Misschien leren ze deze les voordat het te laat is en stappen ze over op het hardere geld, maar misschien ook niet. In beide gevallen is het eindresultaat hetzelfde: de meerderheid van de rijkdom valt toe aan het hardste geld.

Dit proces verklaart de wereldwijde demonetisering van zeeschelpen, glazen kralen, ijzer, koper en andere primitieve betaalmiddelen ten gunste van goud en zilver. Het verklaart ook de demonetisering van zilver in de negentiende eeuw en de scherpe daling van de waarde ervan ten opzichte van goud, de onbetwiste winnaar van de wereldwijde geldmarkt aan het einde van de negentiende eeuw. Omdat de overgrote meerderheid van de wereldbevolking zich concentreerde op de enige grondstof met de betrouwbaar laagste jaarlijkse groei van het aanbod, kon je overal veilig sparen voor de toekomst, waardoor mensen over de hele wereld werden aangemoedigd om te sparen voor hun toekomst, waardoor hun tijdsvoorkeur afnam. Dit maakte veel spaargeld beschikbaar voor kapitaalinvesteringen, verhoogde de arbeidsproductiviteit, stimuleerde investeringen in technologische innovaties en verhoogde de welvaart.

Naarmate de mensheid gebruikmaakt van monetaire middelen die lastiger te produceren zijn, verbetert ons vermogen om voor onze toekomst te zorgen. Dit maakt transacties met onze toekomstige zelf efficiënter en vermindert de onzekerheid over wat komt. De betrouwbaarheid van geld als spaarmiddel heeft talloze mensen in staat gesteld de verwoestingen van oorlogen en rampen te ontvluchten, met vermogen dat zij gemakkelijk wereldwijd kunnen verplaatsen. Doordat de onzekerheid over de toekomst afneemt en de rijkdom die we naar de toekomst kunnen overbrengen toeneemt, zullen mensen de toekomst minder laag waarderen en daalt de tijdsvoorkeur. In elke samenleving en in elke periode is de kwaliteit van de monetaire technologieën die mensen ter beschikking staan, onafscheidelijk verbonden met tijdsvoorkeur, of dit nu positief of negatief uitpakt.

## Tijdsvoorkeur en sparen

Economische goederen kunnen op drie manieren worden gebruikt: ze kunnen worden geconsumeerd, bewaard voor toekomstig gebruik of geïnvesteerd om meer economische goederen te produceren. Hetzelfde is waar voor geld, een economisch goed dat geoptimaliseerd is om waarde vast te houden in de toekomst. Geld wordt altijd op een van de volgende drie manieren gebruikt: het wordt ingewisseld voor consumptiegoederen, bewaard als kassaldo of ingeruild voor kapitaalgoederen, wat betekent dat het wordt geïnvesteerd in het productieproces van andere goederen, in de hoop dat het een hoger rendement oplevert dan het aanhouden van een kassaldo.

In de moderne economie is het cruciale verschil tussen sparen en investeren grotendeels uit het oog verloren, waarbij deze twee termen vaak door elkaar worden gebruikt. Dit is deels te wijten aan de ongelukkige situatie waarin veel studenten deze concepten hebben geleerd volgens de onlogische principes van het Keynesiaanse gedachtegoed. Voor Keynesianen zijn sparen en investeren instrumenten die gedicteerd worden door overheidsbeleid, zonder dat daarbij rekening wordt gehouden met opportuniteitskosten. Hoewel centrale planningsbureaucrating dit toejuichen, voornamelijk omdat het hun salarissen legitimeert, staat dit ver af van de realiteit.

Het onderscheid tussen sparen en investeren ligt in de verkoopbaarheid en het risico van elke categorie. Sparen verwijst specifiek naar het accumuleren van geld in liquide middelen. De reden voor het aanhouden van contant geld is om zich in te dekken tegen toekomstige onzekerheid. Als de mens in een wereld leeft waarin alles zeker en perfect voorspelbaar is, dan heeft hij geen reden om contant geld aan te houden. Met de perfect voorspelbare timing van alle toekomstige inkomsten en uitgaven, kan hij al zijn rijkdom aanhouden in investeringen die een rendement opleveren, en ze alleen liquide maken op het moment dat hij geld moet uitgeven. Maar omdat het leven onzeker is en de mens nooit weet wanneer hij geld moet uitgeven, houdt hij liever spaargeld aan om te profiteren van de hoge verkoopbaarheid ervan, zelfs als het niets oplevert. Investeringen leveren wel rendement op, maar ze zijn minder goed verkoopbaar, moeilijker liquide te maken en brengen het risico van verlies met zich mee. Wanneer een mens zijn investering liquide moet maken om geld uit te geven, loopt hij het risico dat hij niet in staat is om iemand te vinden die bereid is om de prijs te betalen die hij wil op het moment dat hij dat wil. Tijdens systeemcrises, op een moment waarop iedereen investeringen wil liquideren in ruil voor geld, zou de marktprijs ten opzichte van wat de eigenaar verwachtte zwaar gedaald zijn. Daarentegen stijgt de waarde van geld tijdens een crisis als individuen hun uitgaven verminderen en hun investeringen liquideren voor contant geld.

Contant geld stelt eigenaren, zowel particulieren als bedrijven, in staat om zich in te dekken tegen onvoorziene negatieve economische schokken en om te profiteren van positieve economische mogelijkheden. Wanneer de eigenaar van geld een ongeluk krijgt en medische zorg nodig heeft, kan hij of zij direct betalen zonder een investering te hoeven liquideren. Komt er een aantrekkelijke zakelijke kans voorbij, dan kan iemand met liquide middelen direct investeren. Als het geld vastzit in andere beleggingen, is dit wellicht niet mogelijk. De wijsheid van grootmoeder om altijd spaargeld achter de hand te houden, wordt wereldwijd erkend. In een wereld waar het aanhouden van contant geld niet wordt ondermijnd door inflatie, stimuleren investeringen beleggers om een aanzienlijke reserve aan contant geld te behouden als 'droog kruit', zodat ze snel kunnen handelen wanneer zich een goede investeringsmogelijkheid voordoet. Wanneer je al je geld investeert in elke kans die zich voordoet, loop je ongetwijfeld de beste kansen mis, die onverwachts komen en snel worden gegrepen.

Geld wordt slechts voor één eigenschap verworven: zijn verhandelbaarheid of verkoopbaarheid, dus het gemak waarmee het kan worden verkocht zonder een aanzienlijk waardeverlies. De verkoopbaarheid van contant geld wordt bevorderd door het wijdverspreide gebruik, de deelbaarheid, duurzaamheid, verplaatsbaarheid en de verwachting dat het in de toekomst bestand is tegen inflatie. Cash wordt niet aangehouden om rendement na te streven, maar vanwege de liquiditeit en het lage risico op waardevermindering. Een gouden munt of een Amerikaans dollarbiljet is vandaag de dag overal in de wereld zeer goed verkoopbaar. Als je er een bezit en je moet het liquide maken, zal er waarschijnlijk geen tekort zijn aan bereidwillige kopers om het van je over te nemen tegen een prijs die dicht bij de gangbare waarde op de markt ligt. Een huis, een auto, een aandeel in een bedrijf of een mooi schilderij zijn daarentegen veel minder goed verkoopbaar. Als iemand deze goederen moet verkopen, zal het waarschijnlijk enige tijd duren om de juiste koper te vinden die bereid is om de gangbare marktprijs voor deze goederen te betalen. Een huis dat 10 bitcoin waard is, zal deze 10 bitcoin niet meteen opbrengen nadat het te koop is gezet. Veel mensen zullen het huis willen zien, onderzoeken en erover nadenken voordat ze het kopen. Je zult misschien niet snel iemand vinden wiens eisen voor een huis precies overeenkomen met die van het huis dat jij hebt, dus je zult alleen een bod krijgen van mensen die je huis niet hoog waarderen en een lagere prijs bieden. Als je geen andere keuze hebt dan te verkopen, zul je gedwongen worden om met een aanzienlijk verlies te verkopen. Als je een huis wilt verkopen, doe je dat liever niet onder tijdsdruk, zodat je kunt wachten tot de juiste koper die je huis goed waardeert langskomt. Voor onverwachte uitgaven onder tijdsdruk wil je goed verkoopbaar liquide geld achter de hand hebben.

In tegenstelling tot sparen, moet je bij investeren de controle over je kapitaal opgeven, zodat het kan worden ingezet in de productie. Je geeft de verkoopbaarheid en betrouwbaarheid van een kassaldo op om het kapitaal te gebruiken in een productief proces, in de hoop dat het winst zal opleveren. De investeerder offert de liquiditeit van contant geld op en neemt het risico op verlies op zich in ruil voor rendement op zijn investering. Er is geen investering zonder risico, omdat de kans op gedeeltelijk of volledig verlies van het kapitaal altijd aanwezig is.

Tijdsvoorkeur kan worden gezien als de drijfveer achter sparen en investeren. Zodra een individu zijn tijdsvoorkeur kan verlagen om zich bezig te houden met activiteiten die niet onmiddellijk beloond worden, kan hij ervoor kiezen om de huidige tijd op te offeren in ruil voor de toekomst. Zodra men besluit af te zien van consumptie van huidige goederen om ze te sparen voor de toekomst, verlaagt men de tijdsvoorkeur nog verder.

Als je er op een conceptuele en chronologische manier over nadenkt, kan sparen alleen worden begrepen als de voorloper en als voorwaarde van investeren. Ongeacht het kapitaalgoed kan het ook geconsumeerd of geruild worden voor goederen die men in het heden kan consumeren. Voordat men kapitaal kan investeren, moet men eerst de consumptie ervan uitstellen door het te sparen. Hoe kort de periode tussen het verdienen van vermogen en het investeren ervan ook is, die periode is een periode van sparen. Dit is de logica van grootmoeders en hedendaagse vermogensbeheerders uit de hele wereld: verminder je uitgaven om een bepaald bedrag te kunnen sparen dat je nodig hebt als kassaldo, om je te beschermen tegen een slechte dag of een ongeluk, en zodra je dat bedrag hebt bereikt begin je je overtollige spaargeld te investeren in productieve bedrijven.

Men hoeft niet te kiezen tussen ofwel sparen of beleggen, beide hebben hun plaats in een portfolio. De keuze tussen deze twee wordt bepaald op basis van marginale verschillen en is afhankelijk van de hoeveelheid die in elk van beide al aanwezig is. Jonge mensen met weinig vermogen zullen waarschijnlijk de voorkeur geven aan een risicovrij kassaldo voordat ze risicos kunnen nemen op de kapitaalmarkten. Degenen die veel spaargeld hebben opgebouwd, zullen eerder op de kapitaalmarkten beleggen.

Als een individu zijn kassaldo begint op te bouwen vanaf nul, is het marginale nut van het aanhouden van contant geld erg hoog, omdat hij er erg weinig van heeft. Op dit punt is het nut van een kassaldo waarschijnlijk groter dan om het even welke investering, aangezien alle investeringen risicos en een lage verkoopbaarheid hebben, en met een kleine hoeveelheid vermogen wordt verkoopbaarheid gewaardeerd, terwijl risico ongewenst is. Naarmate hij grotere kassaldi opbouwt, neemt het marginale nut van het aanvullen van deze saldi af, totdat het onder het verwachte rendement van de beste investeringsmogelijkheid komt die voor hem beschikbaar is. Hoe meer contant geld de mens heeft, hoe beter hij bestand is tegen het risico van de investering. Een slechte investering zal hem niet ruïneren, omdat hij nog steeds zijn kassaldo heeft.

Het verlagen van de tijdsvoorkeur is wat individuen ertoe aanzet om kassaldi op te bouwen en te investeren. Hoe lager de tijdsvoorkeur, hoe minder ze consumeren en hoe meer middelen ze zullen hebben om te sparen en te investeren. Elke persoon zet geld apart dat hij met zekerheid zou willen hebben, en neemt risico met zijn investering op zoek naar rendement. Bij een harde geldstandaard, zoals een goudstandaard, zou het harde geld zelf worden aangehouden als spaargeld, omdat het door zijn relatieve schaarste elk jaar een beetje in waarde stijgt. In een moderne economie met zacht geld is contant geld 'rommelgeld', zoals elke investeringsmanager weet. In plaats daarvan houden mensen het equivalent van hun spaargeld aan in staatsobligaties of aandelen met een laag risico, en nemen ze meer risico met de rest van hun portfolio.

Sparen en investeren zijn geen concurrenten; investeren volgt op sparen. Beide worden gedreven en voorafgegaan door het verlagen van de tijdsvoorkeur en het uitstellen van voldoening. Wanneer verwacht wordt dat geld in waarde zal stijgen, zullen mensen eerder geneigd zijn om hun consumptie uit te stellen om te sparen in hard geld. Als je spaargeld toeneemt, neemt de mogelijkheid om te investeren ook toe. Als de waarde van kassaldi stijgt, hebben individuen de vrijheid om meer risicos te nemen met hun investeringen. In een wereld met hard geld zouden alleen investeringen met een positief reëel rendement zinvol zijn, in tegenstelling tot het scenario met zacht geld, waar investeringen met een positief nominaal rendement maar een negatief reëel rendement mogelijk zijn, wat leidt tot kapitaalvernietiging in reële termen. In tegenstelling tot wat de Keynesiaanse propaganda beweert, bevordert inflatie investeringen niet, maar leidt het tot een verkeerde allocatie ervan. In Hoofdstuk 6 zagen we hoe het Keynesiaanse model de ongegronde bewering stelt dat spaargeld in een perfect evenwicht moet zijn met investeringen. Vanuit dat perspectief leidt een overschot aan spaargeld ten opzichte van investeringen tot werkloosheid en recessie. Maar in werkelijkheid volgen de investeringen op het opbouwen van spaargeld en hebben ze de neiging om te stijgen als de hoeveelheid spaargeld toeneemt. De keuze om te verdelen tussen consumptie, spaargeld en investeringen is gebaseerd op het marginale nut en wordt bepaald door tijdsvoorkeur. Naarmate de tijdsvoorkeur daalt, verschuiven economische middelen van consumptie naar spaargeld. Naarmate de hoeveelheid spaargeld toeneemt, zal de marginale waardering van de extra beetjes spaargeld afnemen, waardoor het investeringsrisico meer aanvaardbaar wordt.

Naarmate de tijdsvoorkeur afneemt, zijn mensen meer geneigd om hun consumptie uit te stellen, waardoor ze meer geld beschikbaar hebben om te investeren en uit te lenen. Een overvloed aan leenbare middelen maakt het mogelijk om meer productieve bedrijven te financieren tegen lagere rentetarieven. Met een grotere beschikbaarheid van kapitaal neemt de arbeidsproductiviteit toe, wat resulteert in een stijging van het inkomen en de levensstandaard. Deze toename van inkomens leidt op haar beurt tot meer kapitaalaccumulatie, wat resulteert in een opwaartse spiraal van toenemend materieel welzijn. Dit proces staat bekend als beschaving.

## Tijdsvoorkeur en beschaving

Als individuen hun tijdsvoorkeur verlagen en meer kapitaal vergaren, neemt hun productiviteit toe waardoor ze worden gestimuleerd om hun tijdsvoorkeur nog verder te verlagen. In *The History of Interest Rates* laten Homer en Sylla een 5.000 jaar durend proces zien van dalende rentevoeten, verweven met aanzienlijke stijgingen tijdens perioden van oorlog, ziekte en rampen.[@148] De verschuiving naar hardere valuta met een betere verkoopbaarheid over afstand en door tijd kan worden gezien als een bijdrage aan de historische daling van de tijdsvoorkeur, doordat mensen een beter spaarmiddel hebben, waardoor de toekomst minder onzeker voor hen is en ze deze dus minder afwaarderen. Dit resulteert in meer spaargeld en meer beschikbaar kapitaal tegen lagere rentetarieven.

Zolang individuen in staat zijn om kapitaal te accumuleren en ze kunnen verwachten dat het van hen zal blijven nadat ze erin geïnvesteerd hebben, zal dit proces waarschijnlijk doorgaan en een hogere kapitaalsom en een lagere rentevoet genereren. Dit proces kan echter onderbroken en omgekeerd worden door verschillende factoren. Natuurrampen vernietigen eigendom en kapitaal, verlagen de levensstandaard en brengen levens in gevaar, wat leidt tot een hogere afwaardering van de toekomst en een behoefte om meer van de beschikbare middelen in het heden te consumeren, waardoor de kapitaalaccumulatie afneemt en de tijdsvoorkeur toeneemt. Maar door de mens veroorzaakte rampen vormen een even grote, of misschien wel meer voorkomende bedreiging voor eigendom.

Schendingen van eigendomsrechten zijn de belangrijkste sociale en institutionele factoren die de tijdsvoorkeur beïnvloeden. Diefstal, vandalisme en andere vormen van criminaliteit zijn vergelijkbaar met natuurrampen in de zin dat ze de voorraad aan kapitaal en goederen waarover een individu kan beschikken verkleinen, waardoor hij gedwongen wordt om een groter deel van zijn middelen in het heden te consumeren en zijn toekomst onzekerder wordt. Een hoger aantal criminele voorvallen leidt er verder toe dat steeds meer middelen worden besteed aan bescherming tegen criminaliteit, waardoor middelen worden onttrokken aan andere productieve bestemmingen. Hoe meer misdaad, hoe meer middelen moeten worden besteed aan bescherming, wat niet bevorderlijk is voor de welvaart.

Veel belangrijker dan individuele criminaliteit is institutionele of georganiseerde criminaliteit in de vorm van roofzuchtig overheidsbeleid, dat zich aantoonbaar uitstrekt tot alle vormen van met dwang opgelegde regulering, zoals besproken door Per Bylund in *The Seen, The Unseen, and the Unrealized*.[@149] Terwijl het mogelijk is om bescherming te kopen tegen willekeurige individuele criminelen, zijn schendingen van eigendomsrechten door de overheid systematisch, herhalend en onontkoombaar. Omdat ze als legitiem worden beschouwd, is het veel moeilijker om je te verdedigen tegen schendingen van eigendomsrechten door de overheid dan tegen individuele criminaliteit. Het heffen van belasting betekent een lager toekomstig inkomen en een lager rendement op investeringen.

De waarde van een valuta laten wegsijpelen is één schending van eigendomsrechten die zeer destructief is voor toekomstgerichtheid en het verlagen van tijdsvoorkeur. Tijdsvoorkeur is onlosmakelijk verbonden met geld. Het bezit van geld stelt de mens in staat om consumptie uit te stellen in ruil voor iets wat zijn waarde behoudt en gemakkelijk geruild kan worden. Zonder geld zou het uitstellen van consumptie en sparen moeilijker zijn, omdat de goederen in de loop van de tijd hun waarde zouden kunnen verliezen. Je kunt een voorraad graan aanleggen, maar de kans dat het bederft voor het volgende seizoen is groter dan de kans dat een gouden munt waardeloos wordt. Als je het graan kunt verkopen voor goud, kun je het terug ruilen voor graan wanneer dat nodig is en kun je het gebruiken om in de tussentijd iets anders te kopen. In vergelijking met een wereld zonder geld, verhoogt geld op een natuurlijke manier de verwachte toekomstige waarde van het uitstellen van consumptie, helemaal als je dat vergelijkt met een wereld zonder geld. Dit stimuleert het voorzien van je toekomst. Hoe beter het geld in staat is om zijn waarde te behouden, hoe betrouwbaarder het gebruik van dit geld voor individuen is om voor hun toekomstige zelf te zorgen en hoe minder onzekerheid ze zullen hebben over hun toekomstige leven.

Zout, vee, glazen kralen, kalkstenen, zeeschelpen, ijzer, koper en zilver zijn allemaal in verschillende tijden en op verschillende plaatsen als geld gebruikt, maar tegen het einde van de negentiende eeuw draaide praktisch de hele wereld op een goudstandaard. Met de goudstandaard aan het einde van de negentiende eeuw had het grootste deel van de wereld toegang tot een vorm van geld die zijn waarde tot ver in de toekomst kon behouden en tegelijkertijd steeds gemakkelijker over afstand kon worden overgedragen. Sparen voor de toekomst werd steeds betrouwbaarder voor een steeds groter deel van de wereldbevolking. Met de mogelijkheid om te sparen in hard geld, wordt iedereen voortdurend verleid om te sparen, hun tijdsvoorkeur te verlagen en in de toekomst hiervoor beloond te worden. Ze zien de voordelen elke dag om zich heen in de vorm van dalende prijzen en de toegenomen rijkdom van spaarders. De economische realiteit onderwijst iedereen voortdurend over de hoge opportuniteitskosten van huidige uitgaven in de vorm van mis te lopen toekomstig geluk.

De verschuiving naar een makkelijk monetair middel in de twintigste eeuw heeft dit millennia-oude proces van steeds verdergaande verlaging van de tijdsvoorkeur omgekeerd. In plaats van een wereld waarin bijna iedereen toegang had tot een oppotmiddel waarvan de voorraad slechts met ongeveer 2% per jaar kon toenemen, gaf de twintigste eeuw ons een mengelmoes van door de overheid geleverde armzalige munten die, in het minst erge geval, met 6% tot 7% per jaar groeiden, maar meestal met percentages van 2 cijfers voor de komma en soms zelfs met een percentage van drie cijfers voor de komma. Het rekenkundig gemiddelde voor de groei van alle nationale valuta in de periode tussen 1960 en 2020 is 30% per jaar. Het gemiddelde gewogen naar de omvang van de valuta laat een jaarlijkse toename zien van ruwweg 14% in het aanbod van alle fiatvaluta. Dit percentage kan worden gezien als de gemiddelde toename van de geldvoorraad die de gemiddelde burger van de landen met een fiatmunt aan het einde van de twintigste en het begin van de eenentwintigste eeuw heeft ervaren.[@150]

In plaats van te verwachten dat geld in waarde zou stijgen en dus op een betrouwbare manier waarde zou behouden in de toekomst, bracht het fiatsysteem de mensen van de twintigste eeuw terug naar veel primitievere tijden, toen het behouden van waarde voor de toekomst veel minder zeker was en men verwachtte dat de waarde van hun vermogen in de toekomst zou dalen, als het al zou overleven. De toekomst is onzekerder met zacht geld. Deze toegenomen onzekerheid leidt tot een hogere afwaardering van de toekomst en dus tot een hogere tijdsvoorkeur. Fiatgeld belast in feite toekomstige voorzieningen, wat leidt tot een hogere afwaardering van de toekomst en een toename in primitief korte termijn denken bij mensen. Waarom zou je vandaag je consumptie uitstellen als je met je spaargeld morgen minder kunt kopen? Op deze manier verstoren fiatsystemen de natuurlijke economische prikkels en verstoren ze menselijk gedrag, vaak op manieren die het welzijn ondermijnen, zoals ik in meer detail bespreek in *De Fiat Standaard*.

Het toppunt van dit proces is te zien in de gevolgen van hyperinflatie, ofwel de overgang naar een zeer zachte en snel in waarde dalende valuta. Een blik op de moderne economieën van Libanon, Zimbabwe of Venezuela tijdens hun recente hyperinflatoire episodes biedt een goede casestudy, net als de tientallen voorbeelden van hyperinflatie in de twintigste eeuw. *When Money Dies* van Adam Ferguson geeft een goed overzicht van de effecten van hyperinflatie in Duitsland tijdens het interbellum, een samenleving die een paar jaar daarvoor nog een van de meest ontwikkelde ter wereld was.[@151]

In elk van deze scenario's van hyperinflatie werd de waarde van geld vernietigd en daarmee ook de kijk op de toekomst. In plaats daarvan gaat de aandacht uit naar het overleven op korte termijn. Sparen wordt ondenkbaar en mensen proberen al het geld dat ze hebben uit te geven zodra ze het binnen hebben. Mensen beginnen alle dingen die waarde op de lange termijn behouden te negeren, en kapitaal wordt gebruikt voor directe consumptie. In economieën met hyperinflatie worden vruchtdragende bomen omgehakt voor brandhout in de winter en worden bedrijven geliquideerd om uitgaven te financieren -- het spreekwoordelijke zaaigoed wordt opgegeten. Menselijk en fysiek kapitaal verlaten het land en gaan naar de plek waar spaarders het zich kunnen veroorloven om productief te zijn. Nu de toekomst zo zwaar afgewaardeerd is, is er minder stimulans om beschaafd, veilig of legaal te handelen en meer stimulans om roekeloos, crimineel of gevaarlijk te zijn. Misdaad en geweld worden heel gewoon omdat iedereen zich bestolen voelt en zich wil afreageren op degene die iets bezit. Gezinnen gaan kapot onder financiële druk. Hoewel ze extremer zijn in het geval van hyperinflatie, zijn deze trends toch altijd aanwezig, in mildere vormen, onder het juk van de trage fiatinflatie.

Het meest directe gevolg van geld dat zijn waarde geleidelijk aan verliest, is een toename in consumptie en een afname in sparen. Door consumptie en voldoening uit te stellen, moet men plezier in het heden opgeven in ruil voor een beloning in de toekomst. Hoe minder betrouwbaar het ruilmiddel is om waarde om te zetten in toekomstige beloning, hoe lager de verwachte waarde van de toekomstige beloning, hoe duurder de aanvankelijke opoffering wordt en hoe minder mensen geneigd zijn om consumptie uit te stellen. Een extreem voorbeeld van dit fenomeen zie je aan het begin van de maand in supermarkten van landen met een zeer hoge inflatie. Mensen die hun loon krijgen, haasten zich naar de supermarkt om het onmiddellijk om te zetten in boodschappen en primaire levensbehoeften, wetende dat wat ze tegen het einde van de maand kunnen kopen veel minder zal zijn door de vernietiging van de waarde van de valuta. De lage en constante inflatie van fiat doet iets soortgelijks, maar het is subtieler.

De cultuur van opzichtige massaconsumptie die vandaag de dag kenmerkend geworden is voor onze planeet, kan alleen begrepen worden als gevolg van vervormde prikkels die fiat rond consumptie creëert. Omdat het geld voortdurend zijn waarde verliest, zal het uitstellen van consumptie en sparen waarschijnlijk een negatieve verwachte waarde hebben. Dit zet onervaren spaarders ertoe aan om te overwegen in effecten te beleggen. Maar het vinden van de juiste investeringen is moeilijk, vereist actief beheer en toezicht en brengt risicos met zich mee. De weg van de minste weerstand, de weg die de hele cultuur van de fiatmaatschappij doordringt, is om al je inkomen te consumeren en van salarisstrookje tot salarisstrookje te leven.

Als geld waardevast is en in waarde kan toenemen, zullen mensen waarschijnlijk zeer selectief zijn in waar ze het aan uitgeven, omdat de kosten van gemiste kansen na verloop van tijd toenemen. Waarom zou iemand een slechte tafel, een slecht shirt of een slecht huis kopen als ze kunnen wachten en hun spaargeld in waarde zien stijgen, zodat ze een betere kunnen kopen? Aan de andere kant, als mensen voelen dat hun geld snel minder waard wordt, zullen ze minder kritisch zijn over de kwaliteit van hun aankopen. Een slechte tafel, een slecht huis of een slecht shirt lijken dan redelijk, vooral als het alternatief is om geld aan te houden dat na verloop van tijd minder waard wordt, waardoor ze uiteindelijk een product van nog lagere kwaliteit kunnen kopen. Zelfs tafels van lage kwaliteit zullen hun waarde beter behouden dan een valuta die in waarde daalt.

De onzekerheid van fiat strekt zich uit tot al het eigendom. Nu de overheid zich aangemoedigd voelt door de mogelijkheid om uit het niets geld te creëren, verkrijgt ze steeds meer macht over het eigendom van alle burgers, wat ze in staat stelt om te bepalen hoe ze het mogen gebruiken of om het compleet in beslag te nemen. In *The Great Fiction* vergelijkt Hoppe fiateigendom met het zwaard van Damocles dat boven het hoofd van alle mensen met eigendom hangt. Hun eigendom kan op elk moment in beslag worden genomen, waardoor hun onzekerheid over de toekomst toeneemt en hun voorzieningen voor de toekomst afnemen.[@152]

Een ander destructief gevolg van inflatie op vermogensopbouw, is dat de dreiging van inflatie spaarders aanmoedigt om te investeren in alles waarvan ze verwachten dat het een beter rendement zal opleveren dan het aanhouden van contant geld. Met andere woorden, inflatie vermindert de waargenomen waarde van het onderscheidingsvermogen. Als contant geld zijn waarde behoudt en zelfs meer waard wordt, zal een aanvaardbare investering een positief nominaal rendement opleveren, wat ook een positief reëel rendement zal zijn. Potentiële beleggers kunnen kritisch zijn en hun geld aanhouden, terwijl ze wachten op een betere investeringskans in de toekomst. Maar wanneer geld zijn waarde verliest, hebben spaarders een sterke drang om de devaluatie van hun spaargeld te vermijden door te investeren, en dus worden ze panisch om hun rijkdom te behouden. Ze zijn minder kritisch. Investeringen die een positief nominaal rendement opleveren, kunnen toch een negatief reëel rendement opleveren. Bedrijfsactiviteiten die economische waarde vernietigen en kapitaal verbruiken lijken rendabel te zijn als ze worden afgezet tegen de devaluerende valuta en kunnen blijven bestaan, investeerders vinden en kapitaal vernietigen. De vernietiging van vermogen door spaargeld aan te tasten, creëert niet op magische wijze meer productieve mogelijkheden in de samenleving, zoals Keynesiaanse fantasten willen geloven; het herverdeelt dat vermogen in destructieve en mislukte zakelijke kansen. Het creëert ook een enorme industrie van investeringsmanagers om mensen te verkopen wat de goudstandaard hen standaard gratis bood: spaargeld dat in waarde stijgt. Dit is een spel dat alleen verliezers kent: de waarde die verloren gaat aan inflatie om verkwistende overheidsuitgaven te financieren, kan niet door de slachtoffers van inflatie worden teruggekocht. Slechts een fractie zal er in slagen met investeren de inflatie te verslaan, maar men kan er op rekenen, dat de financiële sector, met zijn door de centrale banken verleende monopolistische privileges, aan het langste eind trekt. Het is ook een zeer regressieve belasting: degenen die de inflatie het beste kunnen verslaan met hun investeringen, zijn waarschijnlijk de rijken die het zich kunnen veroorloven om middelen te investeren en markten te bestuderen, niet de armen.

De omgangsvormen en moraliteit die de menselijke samenleving mogelijk maken, hebben er ook onder te lijden als de tijdsvoorkeur toeneemt, omdat het verwaarlozen van de toekomst leidt tot meer interpersoonlijke conflicten. Handel, sociale samenwerking en de mogelijkheid voor mensen om in nauw contact met elkaar te leven in permanente gemeenschappen zijn afhankelijk van het leren beheersen van hun meest basale, vijandige, dierlijke instincten en reacties, en deze te vervangen door verstand en een langetermijnvisie. Religie, beschaafdheid en sociale normen moedigen mensen aan om hun onmiddellijke impulsen te matigen in ruil voor de langetermijnvoordelen van het leven in een samenleving, het samenwerken met anderen en het genieten van de voordelen van arbeidsdeling en specialisatie. Wanneer deze voordelen op lange termijn ver weg lijken, wordt de stimulans om er iets voor op te offeren steeds zwakker. Wanneer individuen hun vermogen zien weglekken, voelen ze zich terecht beroofd. Het vermeende sociale contract lijkt te zijn verbroken en ze twijfelen aan het nut om in een samenleving te leven en haar normen en waarden te respecteren. In plaats van een manier om meer welvaart voor iedereen te garanderen, lijkt de samenleving een mechanisme voor een kleine groep elites om de meerderheid te beroven. Bij inflatie stijgt de criminaliteit en ontstaan er meer conflicten.[@153] Degenen die zich beroofd voelen door de rijke elite van de samenleving zullen het relatief gemakkelijker vinden om agressie tegen andermans eigendom te rechtvaardigen. Een afnemende hoop op een betere toekomst verzwakt de stimulans om netjes en respectvol met klanten, werkgevers en bekenden om te gaan. Naarmate het vermogen om in de toekomst te voorzien in gevaar komt, neemt de wens om er voor te zorgen af. Hoe minder zeker de toekomst lijkt voor een individu, hoe groter de kans dat hij roekeloos gedrag gaat vertonen dat hem op korte termijn kan belonen, maar hem op lange termijn in gevaar kan brengen. Het risico op lange termijn van deze activiteiten, zoals gevangenschap, dood of verminking, wordt verwaarloosd ten faveure van de onmiddellijke beloning van het voorzien in de basisbehoeften van het leven.[^21]

## Tijdsvoorkeur en bitcoin

De opkomst van bitcoin biedt een fascinerende mogelijkheid om het effect van geld op tijdsvoorkeur te begrijpen en om de wereldwijde trend van stijgende tijdsvoorkeur door fiat om te keren. Bitcoin is vrije en open source software voor een peer-to-peer betalingsnetwerk met een eigen valuta. De twee belangrijkste eigenschappen van bitcoin zijn dat de eigen valuta een strikt beperkt aanbod heeft dat volledig ongevoelig is voor de vraag, waardoor het het hardste geld is dat ooit is uitgevonden, en dat het internationale betalingen mogelijk maakt zonder dat er een politieke autoriteit nodig is om toezicht te houden op de transactie. Deze twee eigenschappen -- de hardheid en de weerstand tegen censuur -- geven bitcoin de mogelijkheid om het meest verkoopbare goed te zijn door tijd en over afstand. De schaarste betekent dat het aanbod niet onverwacht verwaterd kan worden, wat het zeer waarschijnlijk maakt dat het zijn waarde in de toekomst zal behouden. En de geautomatiseerde verwerking van betalingen, beveiligd door een echt decentraal netwerk, betekent dat het wereldwijd kan verstuurd worden en dat geen enkele autoriteit de macht heeft om het te censureren of in beslag te nemen.

Bitcoin is vrij makkelijk te gebruiken en het stelt je simpelweg in staat om valuta te bezitten en over te dragen. In de praktijk wordt bitcoin vooral gebruikt als spaarmiddel of vervanging van een spaarrekening. Wereldwijd hebben miljoenen mensen bitcoin gebruikt als spaarrekening, en ze hebben hier enorm baat bij gehad omdat de prijs van bitcoin op de lange termijn aanzienlijk is gestegen.

Dit biedt ons een zeer interessant inzicht in het belang van geld voor tijdsvoorkeur. Democratie, inflatie, roofzucht van de overheid, oorlogen, de Keynesiaanse managersstaat en de overgrote meerderheid van moderne factoren die een toename van de tijdsvoorkeur veroorzaken zijn er nog steeds, en ze worden meestal erger. Toch is bitcoin voor een kleine maar groeiende minderheid van de wereldbevolking een uitweg om te ontsnappen aan de monetaire inflatie. In tegenstelling tot de overgrote meerderheid van de mensen in de afgelopen eeuw, kunnen bitcoiners vandaag de dag sparen voor de toekomst in een monetair middel dat beschermd is tegen devaluatie; ze kunnen met relatief beperkte onzekerheid verwachten dat hun spaargeld in de toekomst beschikbaar zal zijn en dat hun koopkracht zal toenemen. Als geld belangrijk is voor de tijdsvoorkeur, zouden we verwachten dat deze mensen zich onderscheiden van hun fiatgerichte medemensen door een lagere tijdsvoorkeur te hebben. Mijn persoonlijke ervaring van jaren discussiëren met bitcoiners heeft me hiervoor overtuigend bewijs geleverd.

Het verhaal dat bitcoin leidt tot meer spaargeld, kom ik heel vaak tegen. Vóór bitcoin hadden veel mensen gewoon geen idee van sparen en uitgestelde voldoening. Ze gaven al het geld uit dat ze verdienden en als ze grote uitgaven hadden, maakten ze schulden om die te betalen. Ze bleven werken en schulden afbetalen zonder zicht op een einde. Voor zover de meeste mensen investeren, doen ze dat via het pensioenpotje via hun bedrijf. Mensen die wel beleggen zijn meestal degenen die veel tijd besteden aan het bestuderen van de markten en het handelen, waardoor het bijna een baan wordt. Het idee om passief te sparen en tegelijkertijd geld te verdienen met een baan was erg zeldzaam. Na bitcoin werd het steeds gewoner.

Omdat verwacht wordt dat zacht geld na verloop van tijd zijn waarde zal verliezen, is het geen betrouwbare manier om in de toekomst te voorzien; dit vergroot de onzekerheid over de toekomst, wat aanzet tot een sterkere afwaardering van de toekomst, of een hogere tijdsvoorkeur, zoals in de twintigste eeuw werd waargenomen onder de fiatstandaard. Omdat verwacht kan worden dat hard geld zijn waarde in de toekomst behoudt, verhoogt het de potentiële opbrengst van sparen en het uitstellen van voldoening, waardoor de onzekerheid over de toekomst afneemt en sparen en toekomstgericht gedrag worden aangemoedigd, zoals het geval was onder de goudstandaard en in de opkomende bitcoinstandaard. Bitcoin zou de vrije markt oplossing kunnen zijn voor het probleem van de stijgende tijdsvoorkeur. Het is de technologische oplossing die iedereen in staat stelt om opnieuw deel te nemen aan het proces van de verlaging van tijdsvoorkeur, sparen, kapitaalaccumulatie en beschaving. Er is geen politieke toestemming voor nodig, politiek en monetair beleid zijn overbodig, het is niet te stoppen en het is enorm lonend voor iedereen die het omarmt.

[^21]: Voor meer over de sociale, culturele en andere morele implicaties van inflatie, zie ook Salerno, Joseph. “Hyperinflation and The Destruction of Human Personality.” Studia Humana, vol. 2, no. 1, 2013, pp. 15-27. Hülsmann, Jörg Guido. The Ethics of Money Production. Ludwig Von Mises Institute, 2008. Hülsmann, Jörg Guido. Deflation and Liberty. Ludwig Von Mises Institute, 2008