# Bescherming {#sec-bescherming}

Het voorgaande hoofdstuk behandelde argumenten tegen de overheidsinterventie in economische activiteiten en bekeek kritisch de rechtvaardigingen voor dergelijke interventies. Hierbij kwam een absurde verzameling van tegenstrijdige argumenten en duidelijk bevooroordeelde rechtvaardigingen voor deze interventies naar voren. Het initiëren van agressie wordt gezien als een misdaad die rechtvaardiging behoeft, iets waaraan door de staat gefinancierde economen ijverig werken en wat zij graag onder de bevolking verspreiden. Hoe grondiger men deze argumenten onderzoekt, des te duidelijker wordt het dat ze niet te verenigen zijn met de essentiële principes van een kapitalistische markteconomie --- het respect voor eigendomsrechten en een beschaafde samenleving --- die het initiëren van geweld afwijzen.

Al deden klassieke economen van de negentiende en twintigste eeuw veel moeite om het initiëren van agressie in de economische sfeer te verwerpen, ze hebben hun analyse niet uitgebreid naar het bestaan van de staat zelf of de legitimiteit van de voorziening van veiligheid, defensie en wet- en ordehandhaving door de staat. De werken van Murray Rothbard, [^30] Hans-Hermann Hopp, [^31] en vele andere anarcho-kapitalistische geleerden in de Oostenrijkse traditie breiden echter de analyse van menselijk handelen en non-agressie uit naar de oprichting van de staat zelf, de legitimiteit van haar monopolie op geweld en de haalbaarheid van het voorzien van beveiliging, recht en bescherming door een monopolie, gefinancierd via onteigening, [^32]

## De markt voor bescherming

Het is een veelvoorkomende misvatting onder door de staat tewerkgestelde economen dat defensie en geweld buiten het bereik van economische analyses gehouden moeten worden. Maar zoals ik in Hoofdstuk 1 heb besproken, heeft bescherming tegen agressie alle kenmerken van een economisch goed. Het heeft nut, aangezien mensen de voorkeur geven aan het vermijden van de dood en lichamelijk letsel en men wil liever de eigen wil naleven dan onderworpen zijn aan de wil van een ander. Bescherming tegen agressie is ook schaars. Het is niet in onbeperkte hoeveelheden beschikbaar, aangezien agressie een oneindige reeks van potentiële bedreigingen is die op elk moment kunnen ontstaan, terwijl bescherming middelen verbruikt en daarom eindig is en er daarom economisch mee moet worden gehandeld. De combinatie van nut en schaarste maakt bescherming waardevol. Mensen kunnen het produceren of ervoor werken om het van anderen te krijgen. Mensen verlangen ernaar, dus ze zijn bereid ervoor te betalen. Degenen die het leveren, hebben er baat bij om het te verkopen aan bereidwillige klanten. Het is een marktgoed dat mensen kunnen kopen, zoals ze elk ander marktgoed kunnen kopen.

Een belangrijk onderscheid moet hier gemaakt worden tussen geweld an sich en het initiëren van geweld. Bescherming als een goed kan het gebruik van geweld inhouden, maar het betreft niet het initiëren van geweld. Bescherming omvat preventieve maatregelen die geweld minder waarschijnlijk maken, maar ook vergeldende maatregelen die reageren op het initiëren van geweld en degene die het geweld is gestart bestraffen, of een vergoeding zoeken voor het slachtoffer. Het initiëren van geweld is een dwingende handeling waarvan de uitvoering niet vrijelijk door een van de partijen in de transactie kan worden geaccepteerd, dus kan het niet worden beschouwd als een marktgoed. Bescherming tegen het initiëren van agressie en vergelding tegen dergelijke acties is daarentegen een regulier marktgoed dat in een vrije markt zonder agressie te initiëren kan worden gekocht en verkocht. Hoewel bescherming geweld kan inhouden, wordt het gepleegd tegen iemand die al eerder geweld heeft gebruikt. Deze ethische onderscheiding tussen verschillende soorten geweld wordt al erkend sinds de mens voor het eerst ijzer tot zwaarden en schilden begon te smeden, en hetzelfde principe is nog steeds van toepassing op raketten en F-35s.

De markt voor defensie is uitgebreid, gevarieerd en geavanceerd, en biedt een uitgebreid assortiment aan producten en diensten om te voorzien in de behoefte van mensen aan veiligheid en bescherming tegen agressie. Dit omvat voorzieningen zoals veiligheidssloten, alarmsystemen, bewakingscamera's en drones, hekwerken, persoonlijke vuurwapens, gepantserde voertuigen, beveiligingspersoneel en privédetectives. Volgens onderzoekers van The Business Research Company werd de grootte van de particuliere veiligheidssector in 2021 geschat op ongeveer \$303,58 miljard. [@197]

Veel mensen gaan ervan uit dat veiligheid een staatsaangelegenheid is, maar dat is een misvatting. In de huidige wereld, waarin overheden het exclusieve recht hebben om hun eigen krediet als geld te gebruiken en dus onbeperkt diensten kunnen inkopen zolang hun geld wordt geaccepteerd, is de meerderheid van het veiligheidspersoneel wereldwijd in feite privaat aangesteld en niet door de overheid. In 2011 had China bijvoorbeeld 5 miljoen particuliere beveiligers ten opzichte van 2,69 miljoen politieagenten, India had 7 miljoen particuliere beveiligers tegenover 1,4 miljoen politieagenten, en in de Verenigde Staten waren er in 2016 een miljoen particuliere beveiligers tegenover 800.000 politieagenten. Dit patroon was ook zichtbaar in Brazilië, Rusland, Japan, Duitsland, het Verenigd Koninkrijk en in totaal 46 van de 81 landen waarvoor data beschikbaar waren in deze studie. De landen uit dit onderzoek hadden samen een bevolking van 4,9 miljard, waarvan 4,15 miljard in landen leefden waar de meerderheid van de beveiligers privaat was aangesteld. Over de hele steekproef genomen, waren er naar schatting 20 miljoen particuliere beveiligers tegenover 10,5 miljoen politieagenten. Een significant deel van de wereldbevolking leeft dus in gebieden waar het aantal particuliere beveiligingswerknemers het aantal politieagenten ruimschoots overtreft. Deze ongelijkheid is waarschijnlijk nog verder toegenomen in de jaren na het onderzoek, door toenemende problemen met de financiering en werving van de politie, en een stijging in beveiligingsincidenten. [@198]

Hoewel het als een onrealistische techno-utopie kan klinken, is de aanwezigheid van een markt voor bescherming en beveiliging al een realiteit in veel delen van de wereld. De meerderheid van de bedrijven met waardevolle voorraden maakt gebruik van particuliere beveiligingsdiensten om hun ondernemingen te beschermen. Deze opzet is voordelig voor zowel particuliere ondernemers als lokale overheden, wiens beperkte middelen niet toereikend zijn om elke burger en elk bedrijf van de gewenste bescherming te voorzien. Het calculatieprobleem, besproken in Hoofdstuk 12, is ook van toepassing op de veiligheidssector, en de enige oplossing hiervoor is het mogelijk maken van economische berekeningen binnen het kader van duidelijk gedefinieerde eigendomsrechten. In feite is het niet overdreven te beweren dat overheidsveiligheidsdiensten in veel delen van de wereld zich vooral richten op het beveiligen van de overheid zelf, en niet de burgers, die genoodzaakt zijn hun eigen veiligheid te kopen op de markt, door zichzelf te bewapenen of gewapende beveiligers in te huren. Terwijl critici van vrije marktideeën vaak de vraag stellen 'Wie betaalt voor de politie?' alsof het een krachtig tegenargument is, toont de realiteit aan dat individuen en bedrijven al recht, orde en veiligheid buiten de overheid om verkrijgen op de vrije markt voor bescherming.

Het is mogelijk te beargumenteren dat de markt voor bescherming verder reikt dan alleen de genoemde goederen- en politiediensten, en zich ook uitstrekt tot de wereldwijde wapenindustrie. Toegegeven, een aanzienlijk deel van de wapens wordt gebruikt voor agressie en het initiëren van geweld, en een nog groter deel wordt door overheden gekocht met geld dat onvrijwillig verkregen is door belastingheffing of inflatie. Deze markt is dus sterk gemanipuleerd. Niettemin, wapenfabrikanten zijn overwegend vrijwillige private entiteiten die geaccumuleerd kapitaal van spaarders gebruiken, op vrijwillige basis contracten aanbieden en personeel in dienst nemen, grondstoffen inkopen van de wereldmarkten, en hun producten vaak vrij verkopen op de markt aan de hoogste bieder. Van de 100 grootste wapenfabrikanten wereldwijd zijn 68 in privébezit, 24 in overheidsbezit en 6 zijn gezamenlijk eigendom van private partijen en de overheid. [@199] Zelfs overheidsbedrijven functioneren, voor wat betreft hun input en de meeste van hun productiegoederen, binnen de context van een wereldwijde vrije marktordening, profiterend van economische calculatie op basis van bestaande marktprijzen. Alle grondstoffen die nodig zijn voor de productie van wapens worden gekocht op wereldmarkten, die gekenmerkt worden door een uitgebreide arbeidsdeling en vrij geaccumuleerd, privaat kapitaal. Zonder een kapitalistische markt, het streven naar winst, kapitaalaccumulatie, en arbeidsdeling, zou het onmogelijk zijn om wapens te produceren die complexer zijn dan rotsen, speren, pijlen en bogen, en primitieve vallen.

Zodra men de aard begrijpt van gewelddadige conflicten, en het onvermogen om zonder eigendomsrechten economische calculatie te verrichten en een uitgebreide onpersoonlijke arbeidsdeling te realiseren, is deze conclusie onvermijdelijk. Oorlog bestaat immers uit het leveren van grote hoeveelheden kinetische energie met als doel maximale schade aan de vijand toe te brengen. Dit kunnen we in economische zin vergelijken met het leveren van vermogen, zoals besproken in Hoofdstuk 8: het leveren van grote marginale hoeveelheden energie in een korte tijdspanne om specifieke doelen te bereiken. Moderne wapentechnologie wint oorlogen door zo effectief mogelijk en in korte tijdsbestekken kinetische energie te leveren, en onder controle van de gebruiker, zodat er fysieke veranderingen aan de realiteit kunnen worden aangebracht. Denk daarbij aan het doden van vijandige strijders of burgers. Kapitaalaccumulatie, privaat eigendom en de arbeidsdeling zijn het meest effectieve systeem gebleken om de grootste hoeveelheden vermogen te richten op het voldoen van menselijke behoeften. Het is dan ook niet gek dat dit ook de meest effectieve manier is om energie in militaire conflicten in te zetten.

Militair vermogen is ook volledig afhankelijk van een kapitalistische vrijemarkteconomie die de grondstoffen en economische overschotten produceert die kunnen worden gebruikt voor de productie van wapens. Zonder een productieve moderne kapitalistische economie om het te financieren, zou zelfs het sterkste leger ter wereld vervallen tot dwangarbeidskampen die niet in staat zijn om vijanden te verslaan of om zijn eigen soldaten te voeden. De grondstoffen die in de wapenproductie gaan, worden geproduceerd met behulp van uitgebreide wereldwijde productieketens en geavanceerde machines die op een wereldwijde schaal worden ontwikkeld, ontworpen en verspreid. Het is de markteconomie die alle verbazingwekkende vernieuwingen in de wapenproductie heeft voortgebracht en die door criminelen in de openbare en particuliere sector dagelijks worden gebruikt voor het uitvoeren van gewelddadige agressie. De complexiteit van de beschikbare wapensystemen is het gevolg van de ontwikkeling van een markteconomie. De meest geavanceerde wapensystemen van deze wereld zouden nooit kunnen worden ontwikkeld zonder de extreme mate van specialisatie, arbeidsdeling, kapitaalaccumulatie en technologische vooruitgang die alleen mogelijk is in een vrijemarkteconomie. De Sovjet-Unie gaf een zeer groot percentage van haar economische output uit aan de productie van wapens, een percentage dat veel hoger was dan dat van de Verenigde Staten. Maar tegen het einde van de jaren '80 vertaalde deze uitgave zich in enorm dure stapels disfunctionele roest. Ondertussen had de particuliere wapenindustrie van de Verenigde Staten enorme vooruitgang geboekt in haar wapenarsenaal, terwijl het een kleiner percentage van de economische output aan de ontwikkeling van wapens uitgaf.

De Sovjet-industrialisatie profiteerde van het bestaan binnen een globaal kapitalistisch systeem waarmee het handelde en op basis waarvan het prijzen kon berekenen. Enkele jaren na het begin van het socialistische experiment, kregen de Sovjets begrip van de enormiteit van het calculatieprobleem. Ze realiseerden zich dat ze moesten vertrouwen op de prijzen van goederen op de internationale markt om de allocatie van middelen te calculeren. Dit was mogelijk een belangrijke reden waarom hun bureaucratische overheid zo lang overleefde. Maar zelfs dat was niet genoeg. Binnenlandse grondstoffen waren allemaal eigendom van de overheid, er was geen markt voor en ze hadden geen prijzen. Daarom konden ze niet het onderwerp zijn van rationele economische calculatie. De wapenindustrie was geen uitzondering. Tegen de jaren '80 werd het duidelijk voor de Sovjetleiding dat het volledig onwerkbaar was om zon enorm arsenaal te beheren met een disfunctioneel economisch systeem.

Er is wellicht geen groter compliment voor vrije handel dan het feit dat het leeuwendeel van de gewelddadige agressie wereldwijd -- uitgevoerd door zowel regeringen als private rechtspersonen -- voornamelijk afhangt van de wapens die door de marktorde worden geproduceerd. De marktorde is op zijn beurt afhankelijk van het uitstellen van consumptie door private personen. Ze bieden vervolgens kapitaal aan ondernemers, die economische calculaties uitvoeren om te bepalen hoe ze op vreedzame wijze werknemers kunnen inhuren en de geproduceerde goederen kunnen verkopen aan de hoogste bieder tegen een winstgevende prijs. De onbeschaafden en gewelddadigen kunnen wellicht trots zijn op hun agressie en verwerping van vrede en samenwerking, maar hun wapenkeuze bij agressie spreekt boekdelen. Ze kiezen er niet voor om afgezonderd van de beschaafde maatschappij te leven, hun eigen wapens te produceren en deze tegen de beschaving te gebruiken. Ze kiezen ervoor om de meest geavanceerde producten van de arbeidsdeling te kopen, zodat ze de productiviteit van hun geweld kunnen verhogen. Ze hebben misschien niet het mentale vermogen om te begrijpen hoe waardevol een vreedzame arbeidsdeling voor hen is, maar hun acties doen dat wel.

## De markt voor orde en handhaving

De markt voor veiligheid en bescherming tegen agressie reikt verder dan alleen de markten voor wapens en politiediensten; deze omvat ook de rechtspraak, ook bekend als arbitrage. Dit biedt mensen de mogelijkheid om gestolen eigendommen terug te vorderen en degenen die agressie plegen, te bestraffen. Hoewel de meeste van de huidige wereldsystemen bestaan uit monopolistische rechtssystemen die nauw verbonden zijn met het politieke systeem, betekent dit niet dat arbitrage en gerechtelijk toezicht exclusief door de staat uitgevoerd kunnen worden. De Britse common law is voornamelijk ontwikkeld door private rechtbanken die niet onder de bevelen van de overheid vielen. [@200] Deze private rechtbanken boden hun diensten aan aan elke burger die van hun diensten gebruik wilde maken, en ze hadden er alle belang bij om zo eerlijk en onpartijdig mogelijk te zijn om meer klanten aan te trekken. Deze rechtbanken hadden geen monopolie over territoriale jurisdicties en hun werkgebieden overlapten elkaar, wat burgers de vrijheid gaf om een rechtbank te kiezen die ze vertrouwden, in plaats van beperkt te zijn tot hun lokale jurisdictie. Rechters werden aangemoedigd om naar eeuwenoude precedenten en beslissingen te kijken bij het beoordelen van hun zaken, waardoor de common law zich ontwikkelde zonder de inmenging van een centrale planner. Handelsrecht en maritiem recht zijn op vergelijkbare wijze ontstaan in private rechtbanken. Deze onafhankelijke en competitief vrije rechtspraak heeft naar verluidt een grote rol gespeeld in de ontwikkeling van vrije markten en ondernemerschap in Groot-Brittannië, en was ook zeer bevorderlijk voor de Industriële Revolutie die de wereldeconomie ingrijpend veranderde.

Zelfs vandaag de dag hebben de meeste landen groeiende en bloeiende private rechtbanken, waar individuen en bedrijven hun geschillen kunnen voorleggen aan onafhankelijke derde partijen. De private arbitrage-industrie ziet een snel groeiende vraag vanwege de uiterst efficiënte werking in vergelijking met staatsrechtbanken. De American Arbitration Association, een van de vele organisaties in deze snelgroeiende industrie, behandelt elke maand ongeveer 40.000 zaken. Naarmate het Amerikaanse rechtssysteem langzamer, duurder en minder efficiënt wordt, kiezen steeds meer mensen ervoor om hun rechtszaken aan te kaarten bij private rechtbanken. Dit komt doordat arbitrage, net als bescherming, appels of autos, gewoon een marktgoed is zoals elk ander: schaars, nuttig en dus heeft het voor veel mensen een subjectieve waarde.

De groei van de industrie en het bestaan van een geschiedenis met een onafhankelijke rechtspraak tonen duidelijk aan dat het waardevol is om een contractueel geschil tussen twee partijen voor een onafhankelijke derde partij te brengen. Een toenemend aantal commerciële contracten bevat clausules waarin beide partijen verwijzen naar onafhankelijke arbitrage in het geval van geschillen. In een onderzoek onder 26 grote bedrijven uit 2008 ontdekten onderzoekers dat 77% ervan arbitrageclausules heeft in consumentencontracten en 93% in arbeidsovereenkomsten. [@201] Het is voor beide partijen aantrekkelijk om arbitrageclausules op te nemen in het contract, omdat ze beide graag elk geschil goedkoop en snel willen oplossen. Brancheprofessionals, advocaten, rechters en juridische geleerden hebben allemaal een financiële prikkel om arbitragediensten aan hun klanten aan te bieden -- en om deze eerlijk, onpartijdig, efficiënt en snel te leveren. Overheidsrechtbanken, die centraal gepland en aangestuurd worden, zijn meestal veel duurder dan private arbitrage, dus zijn ze voor veel toepassingen onpraktisch. Ook missen ze meestal de expertise over zeer complexe technische of commerciële vraagstukken. [@202]

De groeiende industrie van onafhankelijke arbitrage en de rijke historie van private onafhankelijke rechtbanken laten ons inzien dat er niets speciaals is aan rechtspraak, wat ervoor zou zorgen dat private arbitrage onmogelijk zou kunnen bestaan op de vrije markt. In interacties tussen individuen en bedrijven bestaat altijd de mogelijkheid van een geschil, daarom zullen mensen liever een beroep doen op een onafhankelijke derde partij waarop ze kunnen vertrouwen dat het rechtvaardige beslissingen neemt in geval van geschillen. Het is niet nodig om een rechtsprekend monopolie op te leggen aan alle contracten. Individuen en contracterende partijen zijn zelf in staat om vooraf onafhankelijke derde partijen overeen te komen waarop ze een beroep kunnen doen in geval van geschillen. Bij afwezigheid van een staatsmonopolie voor recht en bescherming, zal de maatschappij waarschijnlijk een bloei zien van winstgevende en non-profitorganisaties. Deze zullen bescherming en handhaving aan de mensen bieden en zullen de volledige verantwoordelijkheid dragen van hun uitspraken, zonder de mogelijkheid om consumenten te dwingen hiervoor te betalen. In *Private Governance* presenteert Edward Stringham een fascinerende en zeer verhelderende studie van verschillende soorten vrijwillige regelingen voor het bieden van recht en bescherming die gewelddadige monopolies onnodig maken.

## Overheidsmonopolie van recht en bescherming

Zoals eerder besproken sprak Mises zich uit over het 'behoud van privaat eigendom van de productiemiddelen en de bescherming hiervan tegen gewelddadige of frauduleuze inbreuken'. Hij had echter een andere opvatting over de legitieme rol van de staat dan tegenwoordig gangbaar is en benadrukte het belang van het recht op zelfbeschikking, waardoor de overheid een vrijwillige entiteit wordt. Hij schrijft:

::: blockquotebox
Het recht op zelfbeschikking betekent met betrekking tot de kwestie van het lidmaatschap van een staat dus dat als de inwoners van een bepaald gebied, of het nu een enkel dorp, een district of een reeks aangrenzende districten is, via een vrij uitgevoerde volksraadpleging kenbaar maken dat zij niet langer verenigd willen zijn met de staat waartoe zij op dat moment behoren. Ze maken kenbaar dat ze ofwel een onafhankelijke staat willen vormen, of zich willen aansluiten bij een andere staat, deze wensen gerespecteerd en nagekomen dienen te worden. Dit is de enige haalbare en effectieve manier om revoluties en burger- en internationale oorlogen te voorkomen. \... Het zelfbeschikkingsrecht waarover wij hier spreken is echter niet het zelfbeschikkingsrecht van naties, maar het zelfbeschikkingsrecht van de inwoners van elk gebied dat groot genoeg is om een onafhankelijke administratieve eenheid te vormen. Als het op een of andere manier mogelijk is om dit recht op zelfbeschikking aan ieder individueel persoon toe te kennen, zou dit moeten worden gedaan. [@204]
:::

Als het volk het recht op afscheiding heeft, kan de staat de loyaliteit en de belastinginkomsten van haar burgers niet als vanzelfsprekend beschouwen en moet ze er hard voor werken. Zonder het recht op afscheiding wordt de overheid een dwingend territoriaal monopolie. Als de bescherming van privaat eigendom een gewild goed is, waarom zou een dwingend monopolie er dan in slagen om dit te leveren? En als het dit economisch goed kon leveren, waarom zou het dan ook niet lukken om andere goederen aan te bieden? Waarom zijn er in alle markten calculatieproblemen, maar niet op de markt voor recht en bescherming? Rothbard weerlegt enkele van de meest gangbare rechtvaardigingen voor een staatsmonopolie op orde en handhaving in *For a New Liberty*. [@205]

Staatsgerichte economen beweren soms dat de overheid nodig is om eigendomsrechten vast te stellen, argumenterend dat zonder een monopolie op het referentiekader voor rechtvaardige aanspraken op eigendom, het onmogelijk zou zijn om eigendomsrechten te definiëren op een conflictvrije manier. Deze bewering is echter ongegrond. Zoals besproken in Hoofdstuk 5, wordt het organiserende referentiekader voor eigendom bepaald door de principes van zelfbeschikking, het eigendom van grondstoffen die door iemands arbeid zijn verkregen en getransformeerd, en het eigendom van goederen die door wederzijdse ruil zijn verkregen. Buiten socialistische samenlevingen bepaalt de staat niet zelf wat eigendom is, maar treedt het slechts op om deze principes te handhaven in geval van eigendomsdisputen. Er is, gegeven deze welomlijnde principes, geen enkele reden waarom handhaving niet door private partijen kan worden verzorgd zonder terug te vallen op financiering via een monopolie.

Een ander argument voor een dwingend monopolie op recht en bescherming stelt dat eigendom een voorwaarde is voor alle economische activiteit, en dat er geen economische activiteit kan zijn zonder dit recht. Echter zijn veel andere goederen zoals voedsel en land essentieel, en zijn vrijwillige overeenkomsten duidelijk een betere basis voor de productie ervan dan een dwingend monopolie. In plaats van een onvermijdelijk gevolg van de vrije markt, ligt het dwingend monopolie op recht en bescherming aan de basis van de vele tekortkomingen van deze markten. Als recht en bescherming dus economische goederen zijn, waarom zouden de tekortkomingen veroorzaakt door een dwingend overheidsmonopolie dan niet ook op deze goederen van toepassing zijn?

Als het volk de legitimiteit van dwangmatige monopolistische voorziening van een bepaald economisch goed accepteert, zullen ze een verslechtering in de kwaliteit van het goed dat zij ontvangen, tekorten in aanbod, en stijgingen in kosten ervaren. De monopolistische aanbieders hebben daarentegen doorgaans baat bij hun bevoorrechte economische positie, waarin zij betaling kunnen afdwingen van hun klanten ongeacht de kwaliteit van de dienstverlening. Dit is precies de situatie waarin staatsveiligheid en -verdediging in het merendeel van de wereld vandaag verkeert. Mensen in overheidsposities profiteren enorm van hun monopolistisch privilege, terwijl consumenten lijden onder een gebrek aan bescherming en onrechtvaardigheid van de wet. De zaken worden nog erger gemaakt door regeringen die hun monopolie over geld misbruiken om uitgebreide propagandacampagnes te financieren op scholen, universiteiten, en massamedia om de acceptatie van de legitimiteit van dwangmatig monopolie over het recht en bescherming te bevorderen. Hoe meer tijd men besteedt aan het onderzoeken van moderne door de staat gefinancierde scholen en universiteiten, hoe meer het opvalt dat het de acceptatie van de staat door de studenten probeert te bevorderen.

Hoofdstuk 8 presenteerde het argument dat moderne machines met hoog vermogen de drijvende economische kracht zijn geweest achter de afschaffing van slavernij, omdat ze meer zware arbeid kunnen produceren tegen veel lagere kosten dan mogelijk was met slaven. Met moderne machines en krachtige energiebronnen, wordt de fysieke arbeid van mensen steeds goedkoper, aangezien hun productiviteit stijgt terwijl intellectueel werk -- het toezicht op machines -- steeds waardevoller wordt. Het is niet langer winstgevend om mensen in de traditionele zin tot slaaf te maken, maar dat heeft de oude dynamieken van slavernij en overheersing, die al millennia in menselijke samenlevingen bestaan, niet teniet gedaan. Het staatswezen is de uitlaatklep voor het oude, basale dierlijke verlangen om anderen te overheersen en tot slaaf te maken in plaats van met hen beschaafd samen te werken. In plaats van fysieke slavernij, maakt het statisme echter massapsychologische slavernij van samenlevingen mogelijk via de inprenting van het idee dat mensen geen andere keus hebben dan zich te onderwerpen aan, en te buigen voor, een gewelddadige monopolistische aanbieder van veiligheid. Slaven werden dus vrijgemaakt van het zware werk en hun boeien zodat ze productievere manieren kunnen zoeken om hun doelen te bereiken. Ondertussen kunnen de individuen die de staat vormen een groot deel van de vruchten van de arbeid van hun onderdanen oogsten door hen via propaganda en onderwijs één monopolistische aanbieder van recht en bescherming te doen accepteren -- en ze ervoor te laten betalen.

Als defensie wordt behandeld als een goed als alle andere, streven producenten in deze sector ernaar om dit zo goedkoop, efficiënt en effectief mogelijk te leveren. Private beveiligers luisteren veel beter naar de behoeften van hun klanten, juist omdat hun hele businessmodel afhangt van hun efficiëntie door het feit dat ze geen monopoliepositie hebben. Problemen ontstaan echter wanneer staatspropaganda burgers ervan overtuigt dat defensie (of bescherming) een bijzonder goed is -- en wanneer mensen zijn opgeleid en geconditioneerd om te denken dat ze geen andere keus hebben dan onderworpen te blijven aan de regering waar ze onder geboren zijn. Dit is waar nationalisme en diverse vormen van overheidspropaganda van pas komen. De moderne slaaf wordt niet in fysieke ketens gehouden, omdat zijn fysieke vrijheid hem te productief maakt om te beperken. Hij wordt in plaats daarvan vastgehouden in een mentale kooi, gecreëerd door staatsonderwijs, en hij accepteert inferieure beveiliging terwijl zijn rijkdom wordt geplunderd, zonder dat er echte verantwoording voor wordt afgelegd of dat hij de keuze heeft om uit het systeem te stappen. Zolang een meerderheid van de bevolking blijft geloven dat het noodzakelijk is om veiligheid te ontvangen als een gift van een hopelijk welwillend monopolist, zal de productie waarschijnlijk tekort schieten, zoals het geval is bij alle marktmonopolies.

De strijd om beschaving is gelijk aan het streven van mensen om elkaar te behandelen op basis van het non-agressieprincipe, waarbij iedereen instemt met het respecteren van de eigendomsrechten van ieder ander en hun rechtmatig verworven eigendom. Wanneer dit principe wordt genegeerd door een gewelddadige monopolist, begint de uitzondering door te sijpelen in alle andere aspecten van het leven, want de monopolist zal proberen alle andere aspecten van het leven te controleren. Doordat de bevolking geconditioneerd is om blindelings de legitimiteit van gewelddadige dwang in de context van recht en bescherming te accepteren, is het niet erg moeilijk om dit uit te breiden naar andere aspecten van het leven, beginnend met geld, zoals in moderne fiatkapitalistische economieën, en eindigend met het concept van eigendom zelf, zoals in communistische samenlevingen. Sociale relaties kunnen niet worden geregeld op basis van respect voor eigendomsrechten wanneer de handhaving van dit eigendom zelf is gebaseerd op een organisatie die door haar eigen bestaan deze eigendomsrechten schendt. De overheid is tenslotte gedefinieerd als de organisatie die zichzelf niet vrijwillig financiert, en dus moet overgaan tot het opleggen van belastingen op haar onderdanen. Dit is de erfzonde van de overheid, die haar volledig onverenigbaar maakt met het creëren van een beschaafde sociale orde op basis van vrijwillige samenwerking. Zoals Hoppe uitlegt, is het zinloos om te verwachten dat de bescherming van eigendommen wordt uitgevoerd door een organisatie wiens bestaan afhangt van het dwangmatig onteigenen van eigendom:

::: blockquotebox
Zodra het principe van de overheid -- als gerechtelijk monopolie met de macht om belastingen te heffen -- ten onrechte wordt gezien als rechtvaardig, is de gedachte dat overheidsmacht beperkt wordt en dat individuele vrijheden en eigendom gewaarborgd worden, een illusie. In plaats daarvan zullen onder monopolistische machthebbers de prijs van rechtvaardigheid en bescherming voortdurend stijgen en de kwaliteit van rechtvaardigheid en bescherming dalen. Een door belastingen gefinancierd beschermingsorgaan is in feite een contradictie in terminus -- een stelende beschermer van eigendomsrechten -- en zal onvermijdelijk leiden tot meer belastingen en minder bescherming. Zelfs als een regering haar activiteiten uitsluitend zou beperken tot de bescherming van reeds bestaande particuliere eigendomsrechten, zoals sommige klassiek liberale voorstanders van het staatswezen hebben voorgesteld, zou de vraag opkomen van hoeveel beveiliging er precies geleverd moet worden. Overheidsambtenaren, die net als iedereen gemotiveerd zijn door eigenbelang en de afkeer voor het leveren van arbeid, maar gezegend met de unieke macht om belasting te heffen, zullen steevast die vraag hetzelfde beantwoorden: het maximaliseren van uitgaven aan bescherming (waarbij bijna alle rijkdom van een natie kan worden opgeslokt door de kosten ervan) en tegelijkertijd het minimaliseren van de productie van bescherming. Hoe meer geld men kan uitgeven en hoe minder men moet werken om te produceren, hoe beter. [@206]
:::

Door deze redenering hebben Rothbard en Hoppe de tegenstrijdigheid blootgelegd die ten grondslag ligt aan het moderne klassiek liberale denken en hebben ze een coherent anarcho-kapitalistisch alternatief voorgesteld dat de principes van de economie, als de studie van menselijk handelen, eerbiedigt.

In plaats van vreedzame samenwerking onder een wettelijk stelsel dat voor iedereen geldt, ontstaan er binnen een samenleving met een overheid uiteindelijk competitieve conflicten en agressie tussen mensen die proberen de macht te grijpen zodat ze anderen kunnen domineren. Een veelvoorkomend bezwaar onder de voorstanders van staatsmacht is het idee dat binnen een vrije markt voor bescherming, de grootste, machtigste groep schurken de maatschappij zal overnemen en controleren. Het anarchistische antwoord hierop is dat dit simpelweg de realiteit is van wat de staat is. Sympathisanten van het staatswezen gebruiken hun eigen cognitieve slavernij als argument voor de noodzaak van het bestaan van de staat. In werkelijkheid is de staat de grootste groep schurken, en de vooruitgang van de menselijke beschaving hangt af van het beperken van de schade die deze bende aanricht, in plaats van de onmogelijke taak om te proberen zijn licentie voor het kwaad te laten gebruiken voor het goede. In samenlevingen waar de meerderheid van de bevolking het waanzinnige idee accepteert dat de overheid een monopolie moet hebben op de aardappel- of elektriciteitsmarkt, eindigt de samenleving met enorm disfunctionele aardappel- en elektriciteitsmarkten. Zo zal een samenleving die een overheidsmonopolie op de markt voor bescherming en beveiliging accepteert ook lijden onder disfunctionele defensie en veiligheid.

Het is dan ook geen verrassing dat tegenwoordig een groeiend deel -- mogelijk een meerderheid -- van de veiligheid en defensie op de markt wordt aangeboden door private instellingen. Gezien de agressieve aard van de vervolging van misdaden tegen de staat in vergelijking met de vervolging van misdaden door de staat tegen gewone burgers, is het niet overdreven om te stellen dat het doel van de staatsveiligheid is om de staat te beschermen, niet het volk. Mensen moeten nog steeds werken en betalen voor hun eigen beveiliging via de verschillende mogelijkheden die op de markt beschikbaar zijn. Een vrije markt voor beveiliging is geen hypothetische situatie. Een dwingend monopolie in de productie van veiligheid dat door belastingen gefinancierd wordt en er daadwerkelijk in slaagt veiligheid te bieden, is daarentegen de hypothetische situatie die door het staatsonderwijs als vanzelfsprekend wordt beschouwd.

## Manieren waarop het staatsmonopolie faalt

Wanneer we het door de lens van menselijk economisch handelen bekijken, kunnen veel van de veiligheidsproblemen van de wereld vandaag worden gezien als het resultaat van de afwezigheid van een vrije en concurrerende markt die voorziet in bescherming, veiligheid en recht. Deze industrieën en veel van hun vitale functies worden nu door monopolistische aanbieders overheerst. Bij afwezigheid van een vrije markt voor deze goederen hebben centrale planners geen rationele manier om middelen toe te wijzen om het beste aan de wensen van de belastingbetaler te voldoen, omdat het geld onvrijwillig afhandig wordt gemaakt en er geen vrije keuze is. Bescherming is uiteindelijk een goed dat niet in oneindige hoeveelheden kan worden geleverd. Er moeten rationele economische beslissingen worden genomen over de toewijzing van specifieke middelen en welke eindproducten men moet proberen te produceren. In de staatsgezinde retoriek en propaganda, waarin marginale analyse niet wordt begrepen, wordt bescherming gepresenteerd als een aan/uit-knop, een compleet pakket van duidelijk gedefinieerde goederen dat op een bekende manier wordt geleverd. Maar met het begrip van marginale analyse kunnen we zien dat bescherming marginaal wordt geleverd, in de vorm van allerlei goederen en diensten die specifiek zijn voor de tijd en plaats waarin ze worden geleverd. Er moeten marginale economische beslissingen worden genomen over het niveau van veiligheid dat aan elk huishouden wordt geboden, maar ook over de inzet van elke individuele politieagent en elk wapen. Moet elke buurt een 24-uurs politiepatrouille krijgen? Of elke straat? Of elk huishouden? Moet de politie meer tijd besteden aan het beschermen van rijke huizen en wijken omdat ze meer kans lopen om het doelwit te zijn van inbraak? Maar waarom zouden arme belastingbetalers moeten betalen om de rijken te beschermen? Hoeveel politieagenten heeft een bepaalde buurt nodig? Moeten sommige mensen bodyguards krijgen? Moeten sportevenementen en concerten extra politiepatrouilles krijgen om problemen te voorkomen, of moeten de organisatoren van deze evenementen hun eigen beveiliging regelen? Deze vragen zijn erg belangrijk voor de mensen die erbij betrokken zijn en in een vrije markt zouden ze in staat zijn om de best mogelijke allocatie van middelen en eigendom te berekenen om op de meest efficiënte manier aan deze behoeften te voldoen. In een wereld waar een centraal monopolie wordt gefinancierd door belastingen, zullen deze beslissingen echter blindelings worden genomen, zonder prijzen of rationele economische berekeningen in acht te nemen.

Beveiligingsdiensten die gefinancierd worden door belastingen kennen geen economische prikkel om menselijke en monetaire kosten te beperken, omdat klanttevredenheid hun bedrijfsvoering niet beïnvloedt. Hierdoor kunnen ze economisch onverstandige keuzes maken, vrijgesteld van de beperkingen van een operationeel budget of een budget voor de werving en training van personeel. Monopolistische legers en politiediensten kunnen hun werknemers behandelen als inwisselbaar kanonnenvoer, aangezien ze niet worden geleid door ondernemers wiens succes afhangt van hun vermogen tot efficiënte middelenallocatie. Het zorgwekkend trigger-happy gedrag van de hedendaagse politie, berucht om het verwoesten van levens en het in gevaar brengen van zowel politieagenten als burgers, kan niet volledig worden begrepen zonder te wijzen op het ontbreken van marktdiscipline waaraan politiediensten onderhevig zijn.

In een vrije markt voor beveiliging worden private aanbieders niet gesubsidieerd met belastinggeld en moeten daarom economiseren; ze moeten verstandige economische keuzes maken om te overleven en te slagen. Hun focus zal liggen op het minimaliseren van gewelddadige conflicten en, voor zover mogelijk, het streven naar vreedzame oplossingen omdat dit goed is voor hun bedrijfsvoering. Beveiligers in private organisaties hebben lang niet dezelfde slechte reputatie als de politie, juist omdat ze opereren in een vrije markt met verantwoording naar de klant toe, en ze hebben rationele marktcalculatie die hun beslissingen, training en bedrijfsvoering sturen. Private beveiligers laten overal ter wereld zien dat het mogelijk is om beveiliging aan te bieden zonder een monopolie te hebben en zonder belast te zijn met het toepassen en interpreteren van de wet die ons gedrag regelt.

De financiering van beveiligings- en beschermingsdiensten door de overheid via belastingen plaatst deze diensten praktisch boven de wet. In een geschil tussen een overheidsfunctionaris en een burger, heeft de functionaris altijd het voordeel van de steun van een enorme instelling met onbeperkte toegang tot middelen, en is hij geneigd de wet toe te passen op een wijze die de overheid ten goede komt. Dit probleem wordt verergerd wanneer de overheid een gerechtelijk monopolie bezit, omdat gerechtigheid dan ook gemonopoliseerd wordt en onderhevig is aan dezelfde kwalen. Zoals Hoppe uitlegt:

::: blockquotebox
Bovendien zal een juridisch monopolie onvermijdelijk leiden tot een gestage verslechtering van de kwaliteit van het recht en bescherming. Als niemand zich tot het gerecht kan richten, maar alleen tot de overheid, zal het recht worden verdraaid ten gunste van de overheid, ondanks het bestaan van grondwetten en hooggerechtshoven. Grondwetten en hooggerechtshoven zijn staatsinstellingen waarvan de beperkingen die ze de staat opleggen onoverkomelijk worden bepaald door de instelling die ze moeten controleren. Het is dus voorspelbaar dat de definitie van eigendom en bescherming voortdurend zal worden aangepast en dat de reikwijdte van de jurisdictie zal worden uitgebreid in het voordeel van de overheid. Uiteindelijk zal het idee van universele en onveranderlijke mensenrechten -- en met name eigendomsrechten -- verdwijnen en worden vervangen door de gedachte dat wetten ontstaan uit door de overheid gemaakte wetgeving en rechten door de overheid gegeven privileges zijn. [@207]
:::

Wanneer het voor leden van de regering toegestaan is om geweld te gebruiken dat legitiem is in de ogen van de bevolking, dan is de kans zeer groot dat ze dat privilege zullen misbruiken ten gunste van zichzelf. Politieagenten en politici kunnen en hebben hun positie misbruikt om zichzelf te verrijken, andere burgers te domineren en om weg te komen met criminele activiteiten. De manier waarop ze hun taken uitvoeren wordt niet door de markt getoetst en ze hebben geen winstoogmerk om zich in die positie te plaatsen. Ze voldoen aan een groot deel van hun behoefte aan winst door het misbruiken van hun positie. Mensen zijn uiteraard niet heilig, dus het is geen verrassing dat velen hun positie misbruiken. Wanneer ze echter geen speciale wettelijke privileges hebben, moeten ze hun taken uitvoeren naar tevredenheid van hun klanten. Hun motivatie en financieel welzijn hangen dan af van het tevreden stellen van klanten door hen te voorzien van veiligheid op een vrije markt. In een samenleving waarin geweld voor een bepaalde klasse van burgers gelegitimeerd is, worden de motivatie en het financieel welzijn sterk versterkt door het misbruiken van hun privilege, wat de resulterende daling van de klanttevredenheid voor hen grotendeels irrelevant maakt.

Dezelfde dynamiek is ook van toepassing op het nationale leger. Aangezien de financiering van het leger gebaseerd is op monopolistische overheidsbesluiten en niet door vrijwillig betalende klanten wordt verkregen, is er weinig ruimte voor verantwoording aan de mensen die het leger financieren. Het resultaat is misschien het meest zichtbaar in de Verenigde Staten, waar s werelds sterkste leger honderden miljarden dollars aan belasting- en inflatie-inkomen per jaar uitgeeft en overal ter wereld militaire basissen heeft, maar er toch niet in slaagt om het veilig te maken voor een kind in Chicago om naar de lokale supermarkt te lopen. Met een gegarandeerde financiering, ongeacht de geleverde veiligheid, is het een krachtig militair-industrieel complex gelukt om grote hoeveelheden geld naar zichzelf te kanaliseren door te zorgen voor een eindeloze stroom van militaire conflicten waarin de VS betrokken raakt, onder flinterdunne voorwendsels. Dit heeft als resultaat dat de VS minder veilig wordt door de vijandigheid van miljarden mensen die wereldwijd wordt gevoed. Zonder consumentenkeuze is veiligheid een bijkomstigheid in vergelijking met de motivatie van de producent om meer inkomsten veilig te stellen. Het verhaal is niet veel beter in kleinere landen met zwakkere strijdkrachten, waar het militaire apparaat er ook in slaagt om te overleven op het met dwang verkregen defensiebudget. Het leger eindigt vaak als niet meer dan een marionet voor machtigere regionale of mondiale regimes.

Het overheidsmonopolie op veiligheid wordt ook belemmerd door het feit dat zoveel van de eigendom van de samenleving als 'publiek eigendom' wordt gehouden, wat betekent dat er geen duidelijke eigendomsrechten zijn en geen mogelijkheid tot privaatrechtelijke handhaving op deze stukken grond. De term publiek of openbaar eigendom is op zichzelf eigenlijk al een contradictie omdat eigendom wordt gedefinieerd door het vermogen van de eigenaar om met zijn eigendom te doen wat hij wil. Het volk is echter geen uniforme entiteit die collectief kan beslissen wat er moet gebeuren. Iedereen heeft tot op zekere hoogte het recht om openbaar eigendom te gebruiken, maar niemand heeft het recht om het verantwoordelijk te beheren als een eigenaar. Geen enkel individu kan de noodzakelijke economische berekeningen doen om de optimale beveiliging van het eigendom te bepalen, en niemand heeft het soevereine recht om mensen te straffen die het eigendom of zijn bewoners misbruiken. [@208]

De overheid presenteert zichzelf als een leverancier van bescherming, maar in werkelijkheid is het agressie. De overheid initieert agressie tegen haar burgers om haar functioneren te financieren. Het biedt haar 'klanten' niet de mogelijkheid om van haar diensten af te zien. Het is agressie verhuld als bescherming. Een overheid die beschermt tegen agressie is in feite een tegenstrijdigheid. Het Amerikaanse Ministerie van Defensie stond niet zonder reden tot 1947 bekend als het Ministerie van Oorlog.

Hoe kunnen we dus orde en handhaving hebben in afwezigheid van een overheid? Als je begrijpt dat de overheid dwang uitoefent, dan beantwoordt die vraag praktisch zichzelf. Het recht is geen creatie van de staat, net als dat geld of de markteconomie niet door de staat zijn gecreëerd. Natuurrecht is een fenomeen dat verscheidene opeenvolgende beschavingen door de geschiedenis heen erkend hebben en de overheden kregen en behielden hun legitimiteit alleen door het te respecteren. Als een samenleving haar regering niet de legitimiteit gaf om het natuurrecht te schenden door de initiatie van agressie, vormde het een betere organisatie van orde en handhaving. Misdaad en geweld zullen waarschijnlijk altijd bestaan, en het vinden van oplossingen hiervoor is steeds meer een marktgoed. De beschaafde samenleving zoekt constant naar technologische en institutionele oplossingen voor het probleem van individuele agressie, wat iedereen begrijpt als immoreel, en gezien het vermogen van de beschaving om voortdurend te berekenen en te innoveren, zal het waarschijnlijk steeds effectiever worden in het beschermen tegen diefstal, zowel privé als door een overheid. Zoals Rothbard het verwoordt:

::: blockquotebox
En inderdaad, wat maakt de staat anders dan georganiseerd banditisme? Wat maakt belasting anders dan diefstal op een gigantische, ongecontroleerde schaal? Wat maakt oorlog anders dan massamoord op een schaal die onmogelijk is voor particuliere politiemachten? Wat maakt dienstplicht anders dan massale slavernij? Kan iemand zich een particuliere politiemacht voorstellen die wegkomt met een fractie van wat staten keer op keer, eeuw na eeuw, blijven doen? [@209]
:::

## Een vrije markt voor defensie

Zoals besproken in eerdere delen van dit hoofdstuk, bestaat de markt voor defensie, veiligheid, recht en arbitrage al en is deze markt wereldwijd naar alle waarschijnlijkheid verantwoordelijk voor het leveren van veel meer defensie, veiligheid, orde en handhaving aan de mensen dan overheden, en dat tegen veel lagere kosten. Toch wordt de markt ook sterk vervormd, verminkt en ondermijnd door de extreme aanwezigheid van overheidsinterventies en -monopolies in de productie ervan. Dit niveau van overheidsinterventie overtreft waarschijnlijk die in elke andere industrie, met misschien als uitzondering het geld- en bankwezen. Men kan niet anders dan zich afvragen hoe een werkelijk vrije markt de veiligheid en defensie zou aanpakken in afwezigheid van staatscontrole, in een wereld waar burgers veiligheid en defensie zien als een privaat marktgoed, en waarin aanbieders van deze goederen niet de mogelijkheid hebben om belastinggeld af te dwingen, geen bijzondere juridische status hebben en niet boven de wet kunnen opereren.

Als we de huidige staat van de Amerikaanse economie bestuderen, stellen we vast dat productieve burgers gedwongen worden om een groot deel van hun koopkracht in te leveren via belastingen en inflatie, ter financiering van een monopolistisch politie en leger, die zowel in het binnen- als buitenland agressie plegen. Ondertussen zijn met name de grote Amerikaanse steden berucht voor hun onveiligheid. Grote Amerikaanse steden staan wereldwijd bekend voor hun extreem gevaarlijke wijken, en vier Amerikaanse steden behoren zelfs tot de lijst van de vijftig gevaarlijkste steden ter wereld. [@210] Het is verbijsterend hoe weinig Amerikanen en vooral economen tot de zeer voor de hand liggende conclusie komen: de monopolistische productie van defensie door de overheid is buitengewoon duur en hoogst ineffectief.

Stel je voor dat Amerikaanse burgers bevrijd zouden zijn van al de belasting- en inflatiekosten die zij (en de rest van de wereld, dankzij de dollar) uitgeven aan de Amerikaanse politie, het leger en het buitenlands beleid, en dat ze in plaats daarvan hun geld naar eigen inzicht aan hun veiligheid zouden mogen besteden. Stel je voor dat de mensen van Chicago al hun rijkdom die nu naar de politie en het leger gaat, zouden kunnen uitgeven aan veiligheidsdiensten die wel verantwoording aan hen verschuldigd zijn, geen monopolie hebben, geen speciale wettelijke bescherming, geen recht hebben om agressie te initiëren, en geen mogelijkheid hebben om belasting te heffen. Stel je voor hoe veel beter de bescherming zou zijn vergeleken met wat ze vandaag de dag hebben.

Een vrije markt in defensie zal geen monopolies kennen voor defensiegerelateerde goederen en zal de initiëring van agressie door wie dan ook niet tolereren. Het is moeilijk voor de meeste mensen om zich voor te stellen dat zon systeem een afschrikmiddel tegen misdaad zou kunnen bieden. Afschrikking is niet alleen mogelijk in zon wereld, we kunnen beargumenteren dat het zelfs veel effectiever en efficiënter wordt aangeboden. Er zijn grofweg vier manieren waarop een vrije markt vreedzaam, beschaafd gedrag zal bevorderen en geweld ontmoedigen.

Ten eerste wordt zelfverdediging in deze context als volkomen acceptabel gezien. Een anarchistische vrije markt in defensie is geen pacifistische versie van het Hof van Eden. Het is eerder een plaats waar gewelddadige vergelding tegen agressie juist als geldig en maatschappelijk aanvaardbaar wordt beschouwd, en zelfs wordt aangemoedigd. Met de handen van de eigenaars van eigendommen bevrijd van de controle van de staat, zullen dieven en moordenaars twee keer nadenken voordat ze kiezen voor het initiëren van agressie. Het recht op zelfverdediging strekt zich verder uit dan alleen het recht van eigenaren om hun eigen regels en straffen te handhaven. Zelfverdediging omvat ook de rechten van eventuele ingehuurde agenten, wat het voor private beveiligingsbedrijven dus mogelijk maakt om namens de eigenaar straffen op te leggen.

Ten tweede hebben mensen in een vrije markt voor bescherming de vrijheid om zich alleen te binden aan contracten en juridische kaders die vrijwillig zijn overeengekomen, waarbij het oordeel van specifieke autoriteiten en rechtbanken wordt gerespecteerd. Dit houdt duidelijke gevolgen in voor mogelijk wangedrag, contractbreuk of gewelddadige agressie. Je zult alleen mensen inhuren die instemmen met het arbeidscontract van een gerespecteerde arbeidsrechtbank, waarin duidelijk de gevolgen worden aangegeven voor absentie, diefstal of sabotage door de werknemer, maar ook bijvoorbeeld wanbetaling door de werkgever. Je zult alleen eten in restaurants waarvan de eigenaren zich houden aan bepaalde gerechtelijke uitspraken met betrekking tot vergiftiging of conflicten met klanten. Je zult enkel zakelijke contracten aangaan met bedrijven die zich houden aan het ondernemingsrecht van betrouwbare rechtbanken. Er is geen monopolie nodig dat je dwingt om zaken te doen met een specifieke rechtbank; je zult zaken willen doen met een bepaalde rechtbank omdat het een betrouwbare reputatie heeft opgebouwd door mensen te helpen bij het maken van wederzijds voordelige transacties. Mensen zullen akkoord gaan met deze regelingen die hen straffen kunnen opleggen, juist omdat het hen zal helpen zaken te doen met anderen. Met efficiënte uitvoering van van handhaving en vrijwillige acceptatie van de voorwaarden door de private sector, is het veel waarschijnlijker dat mensen zich goed zullen gedragen.

Ten derde zal een vrije samenleving nog steeds in staat zijn om reputatie, uitsluiting, schaamte, vermijding en boycots te gebruiken om mensen te ontmoedigen zich te misgedragen. Dit is bijzonder krachtig in commerciële transacties, waarbij de reputaties van deelnemers aan de vrije markt enorm belangrijk zijn voor het voortdurende succes van bedrijven. Zonder door de overheid uitgegeven vergunningen, kunnen vrije verenigingen van handelaren en professionals zeer zware sancties opleggen aan overtreders en zullen ze een zeer sterke prikkel hebben om illegitiem handelsgedrag uit te roeien. Kredietbeoordelingen, professionele recensies en klantenfeedback zijn allemaal goede voorbeelden van hoe reputatie vandaag de dag waardevol is als economisch goed. De opkomst van het internet heeft bedrijven bewuster gemaakt van hun optreden en ze doen extra moeite om recensenten tevreden te stellen en een goede reputatie op te bouwen. De rol van reputatie is echter niet beperkt tot commerciële transacties; het kan ook van toepassing zijn op zowel kleine als ernstige misdaden. Als leden van een gemeenschap overeenkomen om iemand te schuwen en te weigeren met hem zaken te doen omdat hij een misdaad heeft gepleegd, kan dit dienen als een indirecte letterlijke doodstraf, zelfs als deze niet-gewelddadig van aard is. Als beschaafde mensen het erover eens zijn dat de vruchten van de arbeidsdeling alleen beschikbaar zijn voor degenen die de waardigheid van andermans lichaam en eigendom respecteren, dan zal agressie ervoor zorgen dat de initiatiefnemers ervan niet kunnen profiteren van de uitgebreide arbeidsdeling en zelfs het risico lopen om te sterven van de honger terwijl ze proberen te overleven op basis van hun eigen arbeid. Terwijl het gebruikelijk is voor door de staat gefinancierde economen om ingewikkelde en onrealistische theoretische modellen te construeren waarin markten worden ontspoord door informatieasymmetrie, is in de realiteit marktinformatie zelf een marktgoed, en een vrije markt in informatie en reputatie produceert waardevolle informatie voor marktdeelnemers. Het is ook een zeer effectief afschrikmiddel tegen misleidende en onrechtmatige praktijken.

Ten vierde zal de verzekeringsindustrie waarschijnlijk een proactieve rol op zich nemen bij het aanbieden van veiligheid en het verzekeren van het overleven en welzijn van haar klanten. Mensen waarderen hun tijd en zullen graag iemand betalen om hun tijd op aarde te verlengen en hen veilig en gezond te houden. Met een open markt voor de levering van veiligheid, en een financieel belang bij het overleven van haar klanten, zullen verzekeringsmaatschappijen in een vrije samenleving veel functies kunnen overnemen van de veiligheidsmonopolies van de staat, terwijl ze ook marktcalculatie en discipline in de markt introduceren. Het is niet moeilijk om de synergie te zien die de verticale integratie van diensten als veiligheid, recht en eigendomsbeheer kan bieden. Eigenaren van onroerend goed zullen bijvoorbeeld erg geïnteresseerd zijn om beveiligingsbureaus in te schakelen die een vergoeding vragen om veiligheid te bieden, maar er ook mee instemmen om schadevergoedingen uit te keren wanneer hun klanten benadeeld worden.

Het is moeilijk te voorspellen hoe een vrije markt in defensie eruit zou zien. Stel je bijvoorbeeld voor dat je twintig jaar geleden probeerde de structuur van de computer- of internetindustrie van vandaag te voorspellen. Deze industrie wordt niet ontworpen door een bepaalde entiteit; het evolueert over decennia van ondernemersaanbod en consumentenkeuze, in wat Vernon Smith 'ecologische rationaliteit' noemt, in tegenstelling tot 'constructieve rationaliteit' (besproken in het vorige hoofdstuk). Iets dergelijks zou plaatsvinden in de markt voor veiligheid als het staatsmonopolie zou worden geliberaliseerd. Als een samenleving de legitimiteit van het initiëren van agressie en het monopolie op agressie zou verwerpen, zou dat de abstracte basisregel zijn voor de organisatie van defensie en bescherming, wat zou leiden tot het ontstaan van complexe opkomende manieren van organiseren.

Ook is het niet eenvoudig om te voorspellen welke wetten en regels een vrije samenleving zou aannemen. Dit is een uiterst complex evolutionair proces, dat zal ontstaan uit de handelingen van mensen in plaats van hun vooraf bedachte ontwerpen. Talloze bedrijven in de beveiligingssector zullen verschillende beschermingsregels implementeren, waardoor mensen de gevolgen van elk set aan regels zullen kunnen zien. Mensen zullen de gevolgen kunnen zien van het hebben van een zeer soepel politiebeleid in tegenstelling tot een zeer streng. Biedt een soepele handhaving bijvoorbeeld vergelijkbare resultaten terwijl het minder geld kost, of leidt het tot meer misdaad en kost het meer geld? Mensen zullen op een vergelijkbare manier vrij kunnen kiezen voor of tegen handhavingsbeleid met verschillende niveaus van tolerantie voor het gebruik van verdovende middelen. Een volledig liberale benadering zou het gebruik van middelen volledig buiten het toezicht van het handhavingsbureau plaatsen, waarbij klanten op de zware kosten die gepaard gaan met het handhaven van hun moraliteit ten opzichte van andere drugsgebruikers besparen. Dit kan de winnende formule zijn voor handhavers, maar je kunt ook zien waarom dat misschien niet zo is. Gebruikers van geestverruimende middelen kunnen mogelijk vaker misdaden plegen en betrokken raken bij ongelukken, wat gevaarlijk zou zijn voor de bevolking en de kosten voor de betreffende beschermingsaanbieder en de verzekeringsmaatschappij aanzienlijk zou verhogen. De veiligere en betaalbaardere optie zou kunnen zijn dat de beschermingsbureaus hun leden opleggen om zich te onthouden van bepaalde drugs. Om naleving te garanderen, zouden de bedrijven steekproefsgewijs drugstests bij gebruikers kunnen uitvoeren, met duidelijke criteria voor boetes en straffen in geval van niet-naleving. Drugsgebruikers zullen in dit geval nog steeds vrij zijn om af te zien van deze regelingen en beschermingsbureaus te vinden die hun drugs wel tolereren, maar deze kunnen uiteindelijk veel meer kosten, of ze zullen misschien niet eens bestaan. Op dat moment wordt de drugsverslaafde geconfronteerd met de keuze om de drugs te blijven gebruiken en vrijwel verbannen te worden uit de samenleving omdat niemand met hen te maken wil hebben, of te verhuizen. De wereld zal zich naar alle waarschijnlijkheid van nature geografisch opsplitsen in gebieden waarin mensen verschillende waarden hebben op het niveau van hun consumptievoorkeuren. Misschien zal een plek als Las Vegas, gezien de uitgebreide geschiedenis en reputatie voor hedonisme, blijven fungeren als een magneet voor mensen met een liberale benadering ten opzichte van drugs, alcohol, gokken en prostitutie. Zeer conservatieve plaatsen zoals Saudi-Arabië zullen daarentegen waarschijnlijk bevolkt blijven door conservatieve mensen die niet samen willen leven met mensen die zich overgeven aan deze ondeugden, en daarom zullen beveiligingsbedrijven het zeer moeilijk maken om daar te leven en aan deze activiteiten deel te nemen.

Het vorige voorbeeld biedt opzettelijk geen concrete voorspellingen. Het dient simpelweg om het enorme scala aan mogelijkheden te illustreren voor het vreedzaam opzetten van de verdediging en bescherming van menselijke interactie tot de tevredenheid van alle betrokkenen. Alles wat je wilt dat jouw overheid voor je doet, kan verschaft worden door eigendomsrechten en gespecialiseerde arbeidsdeling -- zelfs de wens om je te distantiëren van mensen die bepaalde middelen consumeren.

De erkenning van zelfbeschikkingsrechten en het eigendom van materiële goederen vormt het enige mogelijke fundament voor het creëren van de uitgebreide marktordening die in de hoofdstukken van dit boek is uiteengezet. Dit is de enige weg waarlangs de menselijke beschaving zich op een vreedzame en productieve wijze kan ontwikkelen. Een begrip van de Oostenrijkse school van economie leidt onvermijdelijk tot een meer libertaire visie op de wereld. Wie op lange termijn waarde hecht aan de duurzaamheid en productiviteit van de marktordening waarop hij vertrouwt, zou moeten streven naar een wereld waar zoveel mogelijk mensen volledige zeggenschap hebben over hun tijd en eigendommen, en in staat zijn om op hun eigen voorwaarden samen te werken.

Er is een naïeve opvatting van libertarisme (onder critici en sommige aanhangers) als een ideologie van verlangenbevrediging en consequentie-ontkenning. Voor deze auteur, en ik geloof voor het merendeel van de economen in de Oostenrijkse traditie, is libertarisme de verwerping van het initiëren van geweld, wat inhoudt dat niemand in de samenleving de verantwoordelijkheid heeft om je gedrag te accepteren of je vrij te stellen van de ongewenste gevolgen. In feite is de vrijheid die libertariërs voor zich zien precies de vrijheid om de gevolgen te ondervinden van je eigen gedrag, zowel beloningen als harde straffen. Een private rechtsorde zou mensen niet proberen te beschermen tegen het lijden van negatieve gevolgen; het zou deze gevolgen aanbieden met een snelheid en efficiëntie die overheidsmonopolies niet kunnen evenaren. Een dief, verkrachter of moordenaar zal effectiever door zijn slachtoffer worden gestraft dan onder een overheidsmonopolie, net zoals dat een ondernemer op de vrije markt effectiever wordt beloond als hij goederen produceert die anderen wensen. Een libertariër verwerpt de legitimiteit van een regering die agressie initieert tegen een vreedzame drugsconsument, maar zou het recht van individuen respecteren om zich te distantiëren van, te weigeren om te werken met, of niet deel uit te willen maken van dezelfde leverancier van beveiliging als een drugsgebruiker.

Volgt uit deze analyse dat een echt vrije samenleving ook vrij van de staat moet zijn? Het is immers moeilijk te voorspellen hoe deze instellingen zich kunnen ontwikkelen. Mogelijk blijven we ook in een steeds vrijere samenleving een instituut houden dat vergelijkbaar is met de functies van de moderne staat. Het kan zijn dat mensen er vrijwillig voor kiezen om lid te worden van verenigingen die dezelfde functies vervullen als de huidige overheid, en deze organisaties zouden dan het exclusief recht kunnen hebben om agressie te gebruiken tegen leden die akkoord zijn gegaan met deze voorwaarden. De mate waarin de staat verenigbaar is met een vrije samenleving is de mate waarin hij het recht op secessie respecteerd, zoals Mises hierboven besprak.

In *The State in the Third Millennium* presenteert Prins Hans-Adam van Liechtenstein een alternatieve visie op de rol van de staat binnen een vrije samenleving, die voornamelijk is gebaseerd op het respect voor zelfbeschikking en het recht op afscheiding. [@211] In plaats van te pleiten voor een volledige afschaffing van de staat als organiserende entiteit, stelt Prins Hans-Adam voor dat gemeenschappen, tot op het niveau van het lokale dorp, het recht zouden moeten hebben om te kiezen bij welke politieke entiteit ze zich willen aansluiten, of om zich af te scheiden en hun eigen entiteit te vormen. In dit model zou de staat onder meer recht en bescherming kunnen bieden, maar de begunstigden behouden altijd het recht om hun staat te verlaten als zij het niet eens zijn met het beleid, zonder dat zij genoodzaakt zijn te verhuizen en hun gemeenschappen te ontwrichten. Dit model introduceert consumentenkeuze en soevereiniteit terug in de overheidstaken, omdat individuele gemeenschappen de optie hebben om zich te onttrekken aan regelingen waarmee ze het niet eens zijn. Het maakt ook de levering van recht en bescherming mogelijk door instituties die deze functies al eeuwenlang vervullen, met de vrijheid om zelf te bepalen hoe ze hun taken uitvoeren. Deze democratische visie streeft ernaar mensen de vrijheid te geven om hun eigen overheid te kiezen, in plaats van enkel de mogelijkheid om de besluiten van een monopolistische overheid, waarvan ze niet kunnen ontsnappen, te micromanagen.

Het model lijkt sterk op de manier waarop marktdeelnemers opereren en hun consumenten succesvol bedienen. Consumenten hebben niet de mogelijkheid om te stemmen over bedrijfsbeslissingen of om leiders aan te wijzen; ze kunnen simpelweg kiezen of ze het eindproduct wel of niet kopen. Op deze manier zijn alle wonderen van de markteconomie tot stand gekomen. De auto, het vliegtuig, de computer en de smartphone zijn niet uitgevonden via een democratisch stemproces voor elke technische beslissing gedurende de hele ontwerpfase. Ondernemers bouwden deze producten en presenteerden ze aan consumenten, waarbij de uiteindelijke keuze om deze uitvindingen te gebruiken of links te laten liggen ze tot een succes of een mislukking maakte. In een wereld waarin de markteconomie de vreedzame samenwerking en levensstandaard blijft verbeteren, kan dit een redelijke manier zijn om recht en bescherming te organiseren onder steeds beschaafder wordende volkeren. Naarmate de economische activiteit steeds meer gedigitaliseerd wordt, en arbeiders mobieler worden, wordt dit soort concurrentie tussen rechtsgebieden steeds gebruikelijker. Een steeds groter aantal mensen verhuist tegenwoordig om te wonen in monarchieën zoals Qatar en de Verenigde Arabische Emiraten, die naast hele lage belastingen tevens zeer weinig politieke rechten bieden.

De visie van Prins Hans Adam op de staat in het derde millennium kan heel overtuigend zijn voor een groeiend aantal mensen, vooral als ze onderzoek doen naar de positieve resultaten van s werelds meest succesvolle koninklijke families. De Japanse koninklijke familie regeert al 2.600 jaar en speelde een cruciale rol in de ontwikkeling van de Japanse beschaving. Ook Europese, islamitische, Chinese en talloze andere beschavingen bloeiden en kwamen op onder monarchaal bewind. Misschien is het instituut van de monarchie wel één van die spontaan opkomende verschijnselen die de moderne geest eenvoudig denkt te kunnen vervangen door een dwingend monopolie, zoals we zagen gebeuren met het grotendeels tragische en bloederige experiment van democratisering in de twintigste eeuw. Het zou kunnen dat de koninklijke familie, geïnvesteerd in haar langdurige voortbestaan, het meest succesvolle marktinstituut is voor de voorziening van recht en bescherming op de lange termijn.

Monarchieën kunnen als het natuurlijke resultaat van dit selectieproces naar voren komen, indien zij worden beschouwd als familiebedrijven die op lange termijn zorg hebben gedragen voor orde en handhaving binnen hun samenlevingen. Als ondernemingen die generaties overspannen, hebben monarchieën mogelijk een lagere tijdsvoorkeur vergeleken met particuliere bedrijven, waarvan de eigenaren zich waarschijnlijk meer op korte termijn winst richten. Een monarch wenst dat zijn nakomelingen in de toekomst over een welvarend en stabiel land regeren, en zal daarom beleid voeren met aandacht voor positieve lange termijn uitkomsten. De belangen van burgers, in hun rol als consumenten, sluiten waarschijnlijk beter aan bij een multigenerationeel familiebedrijf dat verantwoordelijk is voor het bestuur van het land, dan bij een democratie waarin de leiders worden geconfronteerd met hoge niveaus van onzekerheid. In een democratisch systeem worden leiders mogelijk elke paar jaar vervangen, wat kan leiden tot een focus op korte termijn, gericht op het extraheren van rijkdom ten koste van langetermijnbelangen. [@212]

[^30]: Zie: Rothbard: The Ethics of Liberty; Anatomy of the State; Power and Market; For A New Liberty

[^31]: Zie: Hoppe, Hans-Hermann. The Private Production of Defense. Ludwig Von Mises Institute, 2009. Hoppe, Hans-Hermann. The Myth of National Defense: Essays on the Theory and History of Security Production. Ludwig Von Mises Institute, Auburn University, 2003

[^32]: Noot van de vertalers: Ammous gebruikt een breed begrip van defensie dat zowel nationale of territoriale defensie als persoonlijke bescherming omvat.