# Appendix 1 {.unnumbered}

Deze bijlage gaat dieper in op Mises betoog uit Hoofdstuk 1 dat er geen constanten zijn in het menselijk handelen. Het is een diepgaande kritiek op de methoden van de moderne economie, en om dat te illustreren, bekijken we hoe de natuurwetenschappen kwantitatieve relaties formuleren op basis van constanten, aan de hand van het voorbeeld van de algemene gaswet in de thermodynamica. Deze stelt:

*PV =nRT*, waar P de druk in bar is, is V het volume in liters, n is het aantal molen [^9] (waarbij elke mol 6,02214076 x 10e23 atomen is), T is de temperatuur in kelvin, en R de Regnault constante is van 0.083145 L.bar/mol.K.

Het is mogelijk om zon relatie vast te stellen, omdat metingen van daadwerkelijke fysieke verschijnselen worden uitgevoerd in eenheden die constant zijn en duidelijk zijn gedefinieerd door het Internationale Stelsel van Eenheden (SI), dat zeven basiseenheden definieert waarop alle wetenschappelijke metingen zijn gebouwd: de seconde, meter, kilogram, ampère, kelvin, mol en candela. Vanuit deze zeven eenheden kunnen alle andere fysiek betekenisvolle eenheden worden afgeleid.

Een liter wordt gedefinieerd als het volume van een kubus met zijden van 10 centimeter. In de hedendaagse wereld zijn er diverse meetinstrumenten beschikbaar die betrouwbare en consistente metingen van lengte en volume kunnen verrichten. De eenheid 'bar' staat voor de luchtdruk op aarde op een hoogte van 111 meter bij een temperatuur van 288,15 Kelvin, en deze eenheid wordt uitgedrukt in 100.000 pascal aan druk. Barometers, die ontworpen zijn volgens betrouwbare en consistente standaarden, worden ingezet voor het meten van druk in deze specifieke eenheid.

In het verleden werden de kilogram en de meter, en indirect ook de kelvin, gedefinieerd aan de hand van specifieke objecten die in Parijs werden bewaard. Elke graad op de kelvinschaal komt overeen met een verandering in thermische energie van 1,380649x10e-23 joules. De joule wordt op zijn beurt gedefinieerd als de energie die aan een object wordt overgedragen wanneer een kracht van één newton op dat object werkt in de richting van de beweging van de kracht over een afstand van één meter. De newton wordt gedefinieerd als de kracht die nodig is om één kilogram massa te versnellen met een snelheid van één meter per seconde kwadraat in de richting van de toegepaste kracht.

De seconde werd gedefinieerd als één 86.400ste van een dag. Echter, in 1967 werd een nieuwe en nauwkeurigere definitie aangenomen door het Internationale Stelsel van Eenheden, gebaseerd op de cesium-standaard, de meest nauwkeurige en precieze tijd- en frequentiestandaard tot nu toe ontdekt. Volgens deze standaard wordt de seconde gedefinieerd als de duur van 9.192.631.770 perioden van de straling die overeenkomt met de overgang tussen de twee hyperfijne niveaus van de grondtoestand van de cesium-133 atoom bij een temperatuur van 0 kelvin. Sinds 1983 wordt de meter gedefinieerd als de lengte van het pad dat door licht in vacuüm wordt afgelegd gedurende een tijdsinterval van 1/299.792.458 seconden. Deze meting kan worden bepaald, aangetoond en geverifieerd met experimenten.

In 2019 onderging de kilogram een herdefinitie, gebaseerd op de meter, de seconde, en de constante van Planck. Deze constante wordt gedefinieerd als het quotiënt van de energie van een foton gedeeld door zijn frequentie, met een waarde van $6,62607015 \times 10^{-34}$ joule $\times$ seconde. Met deze herdefinitie zijn nu alle basiseenheden van het Internationaal Stelsel van Eenheden (SI) gedefinieerd op basis van onveranderlijke fundamentele natuurconstanten. Deze benadering maakt het mogelijk om wetenschappelijke relaties te gebruiken voor het onthullen van constante natuurlijke fenomenen. Het SI-stelsel identificeert zeven gedefinieerde constanten: de hyperfijne overgangsfrequentie van cesium, de lichtsnelheid, de constante van Planck, de elementaire lading, de constante van Boltzmann, de constante van Avogadro, en de lichtsterkte voor monochromatische straling van 540 terahertz. Deze vormen de basis voor het afleiden van alle SI-eenheden.

In de algemene gaswet vinden we ook de constante van Regnault, die gemeten wordt op 0,083145 L.bar/mol.K. Deze relatie en deze constante zijn herhaalbaar en aantoonbaar. Volgens deze wet kan ieder persoon de druk, volume, temperatuur, en het molgetal van elk gas in een houder meten, en, daarvan uitgaande, de constante van Regnault bepalen en verifiëren dat de relatie standhoudt. Mocht iemand een andere relatie vinden, met een andere waarde voor de constante, dan zou de ideale gaswet weerlegd worden.

Het beschikbaar hebben van deze betrouwbare fysieke eenheden voor metingen stelt ons in staat systematische, reproduceerbare en kwantitatieve wetenschappelijke experimenten uit te voeren. Dankzij deze constanten en meetmethoden is het mogelijk om gecontroleerde experimenten uit te voeren met gassen bij uiteenlopende volumes, temperaturen en drukniveaus. Uit de waarnemingen van deze experimenten worden relaties afgeleid tussen de verschillende fysiek gedefinieerde variabelen. In het bijzonder maakt de algemene gaswet een wiskundige relatie duidelijk tussen druk, volume en temperatuur. Deze relatie wordt als wetenschappelijk beschouwd omdat ze objectief is; ze is niet afhankelijk van enige individuele of subjectieve interpretatie. Iedereen kan deze relatie repliceren en toetsen. Ze heeft de status van een wetenschappelijke wet gekregen, puur omdat een breed en groeiend aantal onderzoekers haar heeft getest en consistent heeft bevonden dat ze opgaat. Sinds Benoît Paul Émile Clapeyron in 1834 deze relatie voor het eerst voorstelde, is er geen enkel experiment geweest dat haar heeft weerlegd.

Al deze eenheden en constanten zijn gedefinieerd op een manier die wereldwijd acceptabel en vergelijkbaar is, evenals verifieerbaar en toetsbaar voor sceptici. Dankzij deze uniformiteit is het mogelijk voor mensen overal ter wereld om deel te nemen aan handel en geavanceerde technische projecten. De betrouwbaarheid van deze eenheden wordt weerspiegeld in het aantal werknemers en technici die dezelfde gereedschappen en apparatuur gebruiken met algemeen overeengekomen normen. Wanneer een Argentijn een in Duitsland ontworpen koelkast koopt die in China is geproduceerd, moet een groot aantal mensen over de hele wereld het eens zijn over de definitie van alle hierboven gedetailleerde wetenschappelijke eenheden om de bevredigende productie en levering van de koelkast te garanderen.

Deze duidelijk gedefinieerde, interpersoonlijk en internationaal overeengekomen eenheden voor het meten van fysieke verschijnselen hebben geen equivalent in de economische wetenschap. Er zijn geen duidelijk gedefinieerde eenheden waarmee de economische waarde, het nut of de tevredenheid kan worden gemeten, en elke beoordeling van de hierboven gedetailleerde standaarden is subjectief. Economische waarde kan alleen ordinaal worden gemeten, op een manier die de waarde van het ene goed vergelijkt met het andere, en niet kardinaal, door een wiskundige waarde toe te kennen aan elk goed. Dit komt doordat waarde, als basis voor de economie, niet wordt gemeten met een fysiek of precies gedefinieerde hoeveelheid; het is eerder een psychologisch ervaren oordeel, zoals besproken in het Hoofdstuk 2 van dit boek.

[^9]: Een mol is de eenheid voor chemische hoeveelheid.
