## Inleiding {.unnumbered}

De overgrote meerderheid van de leerboeken die tegenwoordig op universiteiten worden gebruikt volgen de gangbare maar zeer verwarrende Keynesiaans-Samuelsoniaanse economische traditie. Ik heb jarenlang gedoceerd aan de hand van deze universitaire leerboeken en heb talloze intelligente studenten de klas zien verlaten met meer vragen dan waarmee ze binnenkwamen. Ze vonden het lastig om het nut van de obscure vergelijkingen die ze leerden te begrijpen of om een overtuigende reden te zien om de uitkomsten ervan te geloven. Door de jaren heen heb ik gesproken met tientallen zeer intelligente studenten en afgestudeerden die een vergelijkbare ervaring hadden. Ze deden wat ze moesten doen om het gewenste cijfer te halen, maar ze begrepen geen enkel deel van de leerstof. Ze probeerden zichzelf ertoe te zetten om de logische gedachtensprongen te maken die nodig waren om logica de irrelevante vergelijkingen te snappen, om vervolgens nooit meer aan ideeën van de cursus terug te denken. Als studenten uit een algemeen geaccepteerde leerboek leren, leren ze theoretische modellen kennen die slechts een zwakke link hebben met de werkelijkheid. Slagen voor de cursussen bestaat uit het begrijpen van de modellen, niet van de realiteit.

In mijn colleges nam ik inzichten uit de Oostenrijkse school van de economie op. Studenten vonden dit steevast de meest praktische en intellectueel interessante delen van de cursus, en het deel dat hen blijvende waarde bood na het behalen van een diploma. In de meeste universiteiten van vandaag worden Oostenrijkse ideeën bijna volledig genegeerd. Moderne leerboeken vermelden de Oostenrijkse school zelden, laat staan dat ze hun ideeën uitwerken. Ik moest voortdurend mijn toevlucht nemen tot diverse bronnen over al deze onderwerpen. De meest vooraanstaande Oostenrijkse leerboeken en geschriften, zoals Mises' *Human Action* en Rothbards *Man, Economy, and State*, zijn voor de meeste moderne lezers moeilijk te verteren. Helaas besteden ze te veel tijd aan het aanvechten van de gangbare economische denkwijze, wat op een gegeven moment het verduidelijken van het Oostenrijkse perspectief belemmert.

Ik heb altijd een heldere, beknopte en leesbare samenvatting gewild van de belangrijkste economische ideeën uit de Oostenrijkse traditie, die leidt tot een begrip van het belang van de uitgebreide monetaire marktorde binnen een beschaving. Ik begon de contouren van zo'n leerboek te ontwikkelen voor master- en seniorcolleges die ik gaf aan de Libanese American University. Na het publiceren van *De Bitcoin Standaard* en het vinden van een enthousiaste doelgroep die mijn economische werk waardeerde, besloot ik mijn aandacht uitgebreid te richten op het schrijven van het leerboek waaruit ik altijd had willen onderwijzen. In 2019 besloot ik mijn universitaire baan op te zeggen en zelfstandig te gaan doceren en te publiceren op mijn website saifedean.com. In 2019 en 2020 ontwikkelde ik twee Principles of Economics-cursussen, ECO11 en ECO12, die de ideeën verder uitwerkten die zouden uitgroeien tot dit boek. Door te doceren en interactie te hebben met honderden studenten van over de hele wereld, en bevrijd te zijn van de steeds meer verouderde en elitaire wetenschappelijke tijdschriften en uitgevers van de academische publicatiemolen, kon ik me nu concentreren op het schrijven voor de lezer, niet voor academische commissies. Na twee decennia van universitaire economische studie, vertegenwoordigt dit boek de economische kennis die ik graag had willen hebben toen ik 17 was. Het is wat ik hoop dat mijn kinderen zullen lezen als ze nieuwsgierig worden naar economie.

Dit boek vormt een introductie tot de grondbeginselen van de economie en de economische denkwijze -- voor iedereen een krachtig en nuttig hulpmiddel voor mentale planning. Op een universiteit zou ik dit boek gedurende twee semesters onderwijzen om studenten zo een breed beeld te geven van het onderwerp economie en de economische denkwijze. Dit is meer dan alleen een universitair leerboek, het is geschreven voor een algemeen publiek dat geïnteresseerd is in economische ideeën. Zelfs als je geen economie studeert aan een universiteit, neem je elke dag van je leven economische beslissingen. Ik hoop dat dit boek een beknopte en toepasbare samenvatting biedt van de meest nuttige inzichten van de economische manier van denken. Een manier van denken die nuttig kan zijn bij persoonlijke en zakelijke besluitvorming. Dit boek hanteert schaamteloos een Oostenrijkse benadering. Het gebruikt eenvoudig geschreven tekst om uit te leggen wat veel economen door de geschiedenis heen hebben beschouwd als de krachtigste methoden om economische verschijnselen te begrijpen. Het past de benadering van menselijk handelen toe om de belangrijkste concepten en onderwerpen in de economie uit te leggen, voortbouwend op het werk van de economen van de Oostenrijkse school. Het behandelt belangrijke economische concepten en onderwerpen in een logische volgorde met als doel de lezer een begrip van economie op individueel en maatschappelijk niveau te bieden, evenals de vele implicaties van economie als onderwerp. Het eerste deel van het boek introduceert de fundamentele concepten in de economie en de Oostenrijkse methode. Het tweede deel van het boek, Economie, introduceert de handelingen van individuele mensen bij het nemen van een economische beslissing. Deel III, De Marktorde, onderzoekt het economisch handelen in de sociale context, waarom de kapitalistische economie zich ontwikkelt, en de rol van geld. Deel IV, Monetaire Economie, onderzoekt tijd, rente, en monetaire en financiële economie. Deel V, Beschaving, onderzoekt de economie van geweld en veiligheid en wat ze voor de verdere ontwikkeling van de menselijke beschaving kunnen betekenen.

Elk hoofdstuk van dit boek bespreekt een belangrijk economisch concept en kan worden gelezen als een op zichzelf staand essay over het onderwerp. Maar het is ook gestructureerd als een monografie waarbij deze concepten in een logische volgorde worden gepresenteerd. Het eerste hoofdstuk introduceert de Oostenrijkse methodologische benadering van de economie, geeft een voorbeeld en een vergelijking met de methodologie van de natuurwetenschappen. Hoofdstuk 2 introduceert het fundamentele concept van waarde en legt op basis van het werk van Carl Menger, de grondlegger van de Oostenrijkse school, de subjectieve aard ervan uit, net zoals de concepten van nut en marginale analyse. Hoofdstuk 3 benadrukt het belang van tijd in de economie, de unieke eigenschappen bij het behandelen van tijd als economisch goed, en hoe alle economische handelingen kunnen worden gezien als pogingen om de hoeveelheid en subjectieve waarde van onze tijd op aarde te verhogen. Dit hoofdstuk introduceert ook de cruciale concepten van opportuniteitskosten en tijdsvoorkeur.

Het tweede gedeelte van het boek introduceert de belangrijkste handelingen die mensen verrichten om op individueel vlak economische keuzes te maken. In elk van de hoofdstukken van dit gedeelte wordt een essentieel concept geïntroduceerd en geanalyseerd op basis van de redenen waarom mensen zich er mee bezig houden, het probleem dat het oplost en hoe het mensen helpt om economisch om te gaan met hun tijd. Het eerste en meest basale concept is arbeid, wat wordt behandeld in Hoofdstuk 4. Hoofdstuk 5 legt de economie van eigendom uit, waarom het ontstaat, het probleem dat het oplost en het concept van zelfbeschikking. Hoofdstuk 6 introduceert een specifiek type eigendom, kapitaal, dat bestaat uit goederen die worden gebruikt voor de productie van andere goederen. Ook de kosten van kapitaal, de productiviteit ervan en het verband met tijdsvoorkeur worden besproken.

Hoofdstuk 7 bespreekt technologie als een economisch concept, waarom het de arbeidsproductiviteit verhoogt en de unieke status als een immaterieel economisch goed dat niet schaars is. Het hoofdstuk sluit af met een bespreking van het concept van intellectueel eigendom, en hoe de niet-schaarse aard van informatie verschilt van andere productiegoederen. Energie, het onderwerp van Hoofdstuk 8, is geen conventioneel onderwerp in de meeste economische leerboeken. Ik geloof echter dat het begrijpen van de energiemarkt essentieel is voor het begrijpen van economie, met name omdat de moderne kapitaalintensieve en technologisch geavanceerde markteconomie niet mogelijk zou zijn zonder aanzienlijke toenames in het vermogen van de moderne mens -- het vermogen om grote hoeveelheden energie in korte tijd te gebruiken. Bovendien is het benaderen van economie via de Oostenrijkse methode, door middel van marginale analyse, essentieel om de realiteit van energieproductie in de wereld van vandaag te begrijpen. Terwijl het tweede gedeelte van het boek het individuele economische handelen onderzoekt, bekijkt het derde deel van het boek economisch handelen in een sociale context door andere mensen in de analyse te introduceren en de implicaties ervan te verkennen. Zodra er een andere persoon aanwezig is, wordt ruilhandel mogelijk en hebben beide partijen een stimulans om hieraan mee te doen, omdat het hen beiden ten goede komt. Hoofdstuk 9 legt de logica achter handel uit, de voordelen ervan en de implicaties van de groei van de markt waarin de arbeidsverdeling plaatsvindt.

Hoofdstuk 10 introduceert het concept van geld, waarbij wordt uitgelegd welke problemen het oplost, hoe deze problemen de gewenste kenmerken van geld bepalen en hoe geld mensen helpt economisch te handelen en de waarde en productiviteit van hun tijd te vergroten. Het hoofdstuk legt uit dat geld een product van de markt is en niet van de staat, zoals vaak ten onrechte wordt onderwezen in economische leerboeken. Hoewel dit hoofdstuk geld introduceert, wordt de bredere discussie over monetaire economie overgelaten aan Deel IV, zodat het de discussie over kapitaalmarkten kan volgen, een essentieel onderwerp in monetaire economie. De sociale orde waarin individuen vreedzaam deelnemen aan alle eerder genoemde economische handelingen wordt een marktorde genoemd. Hoofdstuk 11 onderzoekt hoe individuele voorkeuren en economische handelingen leiden tot het ontstaan van prijzen, waarvan het essentiële belang binnen het marktproces wordt uitgelegd. Hoofdstuk 12 legt de term kapitalisme uit in de Misesiaanse traditie en hoe het een systeem van ondernemen is dat onlosmakelijk verbonden is met privaat eigendom en economische calculatie. We onderzoeken Mises' krachtige test om te bepalen of een samenleving een markteconomie heeft en hoe het ons kan helpen de economische geschiedenis te begrijpen.

Deel IV, Monetaire Economie, benadert het onderwerp geld vanuit een Oostenrijks perspectief en dus begint Hoofdstuk 13 met tijdsvoorkeur, en de relatie ervan tot sparen, geld en kapitaalaccumulatie, wat ook krediet en bankieren mogelijk maakt, de onderwerpen van Hoofdstuk 14, dat ook rentetarieven uitlegt en de vraag behandelt of ze kunnen worden geëlimineerd. Hoofdstuk 15 onderzoekt het Oostenrijkse begrip van de conjunctuurcyclus door de onderliggende oorzaak ervan te onderzoeken, namelijk monetaire expansie door de uitgifte van circulatiekrediet.

Terwijl de eerdere delen de functie en vorm van een kapitalistische markteconomie illustreren, en hoe deze alleen kan werken in een systeem dat privaat eigendom respecteert, onderzoekt het vijfde en laatste deel van het boek, Beschaving, de levensvatbaarheid van de kapitalistische beschaving tegen de dreiging van gewelddadige agressie. Hoofdstuk 16 onderzoekt de economie van geweld, zowel in de privésfeer als van de zijde van de overheid, terwijl Hoofdstuk 17 de economie van defensie onderzoekt en laat zien hoe dit slechts een marktgoed zoals elk ander is, dat tegenwoordig grotendeels op de markt wordt geleverd.

Het laatste hoofdstuk van het boek bespreekt het concept van beschaving vanuit een economisch perspectief. Beschaving wordt gezien als een orde die ontstaat wanneer een samenleving vredig, productief, laag in tijdsvoorkeur, coöperatief en innovatief genoeg kan blijven om verbeteringen van de levensstandaard over meerdere generaties te bewerkstelligen. De kosten van deze monumentale uitdaging worden besproken, evenals de kansen op het voortbestaan van de kapitalistische beschaving in het licht van de enorme bedreigingen waarmee ze wordt geconfronteerd.

Dit boek wordt aangevuld door de website saifedean.com/poe, waar je een volledige bibliografie kunt vinden met links naar de lezingen die in dit boek zijn vermeld. Omdat het internet zo gangbaar is geworden, vond ik het logisch om de papieren versie van dit boek te optimaliseren voor de leeservaring door url's uit verwijzingen te verwijderen en een volledige bibliografie op saifedean.com/poe te bewaren. Na het afronden van dit boek zal ik nog een online cursus aanbieden op saifedean.com om deze stof diepgaander te bestuderen.

Dit boek heeft enorm baat gehad bij en is sterk verbeterd als gevolg van de feedback van Ross Stevens, Jeff Deist, Per Bylund, Conza, Allen Farrington, Jonathan Newman, Peter Young en Thomas Semaan. De laatste twee leverden ook uiterst waardevolle hulp bij het onderzoek tijdens het schrijven van dit boek. Ik bedank ook van harte de uitstekende redacteuren wiens grondige en nauwgezette redactie dit manuscript enorm heeft verbeterd: Alex McShane, Steve Robinson, Chay Allen, Renata Sielecki, Magda Wojcik, Evan Manning en Elizabeth Newton. Ik bedank ook Tamara Mikler voor het maken van het grafische ontwerp en Max DeMarco voor het redigeren van het audioboek. Ik ben ook erg dankbaar voor het team achter saifedean.com van Pavao Pahljina, Marko Pahljina, Dorian Antešić, Flora Fontes en Valentino Cnappi voor alle moeite die ze hebben gestoken in het runnen van de website en het regelen van de publicatie.

Dit boek zou niet mogelijk zijn geweest zonder de steun, aanmoediging en feedback van de leden van mijn online leerplatform saifedean.com. Ik ben hen zeer dankbaar dat ze me in staat hebben gesteld om productief te kunnen werken aan het afronden van mijn werk. In het bijzonder gaat mijn oprechte dank uit naar mijn lezers die de publicatie van dit boek hebben gesteund door de gesigneerde exemplaren in voorbestelling te kopen. Bedankt, A Patel, Aaron Macy, Abdulla Al Abbas, Abdullah, Almoaiqel, Ágúst ragnar Pétursson, Aidan Campbell, AJ Garnerin, Alex, Alex Bowe, Alex Voss, Alistair Milne, Amit Barkan, Anderson Thees, Andrea, Bortolameazzi, Andrew Brasuell, Andrew Rosener, Andrew Stange, Anthony Clavero, Antonio Caccese, Ashok Atluri, ben johnson, Bertrand Marlier, BitcoinTina, Blake Canfield, BowserKingKoopa, brian daucher, Brian Kim, Brian Lockhart, Bronson Moyen, Browning Hi-Power 9mm, Bryan Matthieu, Bryan Wilson, Burcu Kocak, Carlo Barbara, Carlos Chida, Caspar Veltheim, Cedric Youngelman, Chase Oleson, Chen YH, Chris Cowlbeck, Christian Amadasun, Christof Mathys, Christopher Lamia, Christopher P Valle, Christopher Pogorzelski, Christopher To, Cletus Reynolds, Dale Williams, Dan Skeen, Dane Bunch, Daniel Ostermayer, Daniel Smith, Dave Hudson, David Heller, David Lawant, Dirk Seeber, Domingo Ochotorena, Dylan Parker, Ed Becker, Eduardo Lima, Edward Cosgrove, Ernest Huttel, Fabian von Schilcher, Federico Quintela, Francisco Reyes, Frank Acklin, Gary Lau, Gary Speed, Gen Shin, Glenn Thomas, Greg Doyle, Haris M, Harlan Robinson, Hayden Houser, hugh starr, Hunter Hastings, Jaap Willems, Jackson Forelli, Jaeger Hamilton, James Seibel, James Weaver, Jason DiLuzio, Jawad Barlas, Jerrold Randall, Jesse Powell, Jim Patterson, Joachim Boudet, John A. Krpan, John Brier, John Dixon, Jon E, Jonas Karlberg, Jonas Konstandin, Jonathan Camphin, Jonathas Carrijo, Jordan Wilby, Jose Areitio Arberas, José Niño, Jules, Julio Neira, Justin Schwartz, Keith G, Kelly Lannan, Kenneth Gestal, Kevin Coffin, Kim Butler, Lachie McWilliam, Larry Salibra, Leo Smith, Luis Alonso, Maksymilian Korzuchowski, Manuel Tomasi, Marco Daescher, Marcus Dent, Marius Kjærstad, Marius Reeder, Martin Brochhaus, Matija Grlj, Matt, Matthew Robin, Matthew Sellitto, Max Cash, Maximiliano Guimarães, Michael Atwood, Michael Culhane, Mike Clear, Mitch Soboleski, Mitchell Vanya, Nate Kershner, Nathan Smith, Neal Nagely, Nelson, Nicholas Sheahan, Nick Giambruno, Niko Laamanen, The Noded Podcast with Pierre Rochard and Michael Goldstein, Odi Kosmatos, Oleg Mikhalsky, Paweł Sławniak, Petar, Petr Zalud, Prince Filip Karađorđević, Raycheslav Karagyozov, Rene Bos, Richard Duke, Robert Koonce, Robin Dea, Ronald Zandstra, Rosie Featherby, Ross Stevens, Rowais Hanna, Ryan Nadeau, Ryan Sandford, Saagar Singh Sachdev, Sam Dib, Sam Shams, Samuel Douglass, Scott Manhart, Scott Schneider, Scott Shell, Seb Walker, Shakti Chauhan, Shaun McFarlane, Simonna Pencev, Stefano D'Amiano, Stephen Labb, Subhan Tariq, Tanner Dowdy, Thierry Thierry, Thomas Jenichen, Tom Karadza, Travis Tripodi, Trevor Smith, vik, Wendy Hiam, Wilfred Tannr Allard, Will Phillips, William Green, William Johnston, Wityanant Thongsawai, Yani Eberding, Yoism, Zachary Hollinshead, Zarak Ortega, Zsuzsanna Glasz.
